In [ ]:
!pip install urllib3

!pip install tqdm

!pip install wheel --user
!pip install pipwin --user

!pipwin install numpy --user
!pipwin install pandas  --user
!pipwin install shapely --user
!pipwin install gdal  --user
!pipwin install fiona --user
!pipwin install pyproj --user
!pipwin install six --user
!pipwin install rtree --user
!pipwin install geopandas --user

!pip install xlrd

!pip install geopandas

In [1]:
import pandas as pd
import geopandas as gpd
import re 
from tqdm import tqdm

## Partie 1 : récupération des données 

Notre table de base est un fichier csv des établissements dans le domaine de la restauration à l'échelle de la France. Il contient un certain nombre d'informations, notamment l'adresse de l'établissement, son annéee de fondation, son nom, sa taille et enfin son numéro de siren (variable legalImmat).

In [2]:
df=pd.read_csv("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/fichier_restaurants.csv",sep=';',header=8,error_bad_lines= False, warn_bad_lines=True)

In [3]:
df

legalImmat country  streetNumber                           streetName  \
0          7340516  FRANCE           NaN                                  NaN   
1         46412375  FRANCE          21.0                    RUE GEN DE GAULLE   
2         66304932  FRANCE           NaN                   COLLEGE DE KOUNGOU   
3         76912112  FRANCE           NaN                              LE COIN   
4        300443124  FRANCE           NaN               LIEU-DIT CAVALLO MORTO   
5        301341517  FRANCE           1.0                 ESPLANADE PARMENTIER   
6        301863668  FRANCE           NaN                     BOIS DE COULANGE   
7        302296629  FRANCE         146.0                      RUE ROBESPIERRE   
8        303406540  FRANCE           9.0                 AVENUE DE STALINGRAD   
9        303797823  FRANCE           NaN                  LA MARE AUX PRETRES   
10       304305519  FRANCE           5.0                      AVENUE DU MAINE   
11       305021909  FRANCE          19.0                    RUE DE LA CHARITE   
12       305426454  FRANCE          23.0                  RUE MARECHAL JOFFRE   
13       305836033  FRANCE           NaN                    CHEMIN DE LA LONE   
14       305836033  FRANCE           NaN                  ROUTE DE BAR LE DUC   
15       305836033  FRANCE          43.0                       RUE DU PLATEAU   
16       306126210  FRANCE           NaN                LIEU-DIT GERBIER JONC   
17       306332362  FRANCE          25.0                   RUE DE LA HUCHETTE   
18       306999137  FRANCE          27.0                      RUE DE NOAILLES   
19       307711895  FRANCE          15.0                      PLACE DU TERTRE   
20       308880228  FRANCE         361.0                  AVENUE DU 15E CORPS   
21       309408797  FRANCE           1.0                         RUE MAUSSIRE   
22       309654457  FRANCE         113.0              RUE DU MARECHAL LECLERC   
23       310187562  FRANCE           NaN                     ALLEE RAY GRASSI   
24       310727979  FRANCE           NaN               LIEU-DIT LA MARIAUDAIS   
25       311160592     NaN          30.0                COURS DE L'ILE SEGUIN   
26       311372569  FRANCE           NaN                         LES PLATANES   
27       311970552  FRANCE          13.0                  RUE DES BAS SABLONS   
28       312274426  FRANCE          22.0                      ROUTE IMPERIALE   
29       312732837  FRANCE           2.0                   PLACE JEANNE D'ARC   
...            ...     ...           ...                                  ...   
242033   824097901  FRANCE           NaN                    RUE DE LA STATION   
242034   824121123  FRANCE           6.0                   RUE DES SERRURIERS   
242035   824145874     NaN           2.0                          R DES CAVES   
242036   824170633     NaN          49.0                      RUE JEAN MOULIN   
242037   824195283  FRANCE          11.0              CHEMIN DU PETIT CASTERA   
242038   824211098     NaN          28.0                          RUE BLANQUI   
242039   824240980  FRANCE          30.0              BOULEVARD DE SEBASTOPOL   
242040   824260178  FRANCE         308.0                     RUE ALBERT CAMUS   
242041   824277594  FRANCE          23.0                  RUE NICOLAS BOILEAU   
242042   824313852  FRANCE           4.0                     BOULEVARD GIRAUD   
242043   824340020  FRANCE          12.0                          RUE LAKANAL   
242044   824352777  FRANCE         243.0                 AVENUE DE VILLENEUVE   
242045   824374318     NaN          13.0                         R DE VIGNORU   
242046   824401830     NaN          55.0                  RUE DU GENERAL BUAT   
242047   824429237     NaN          12.0                         RUE DE DREUX   
242048   824462725     NaN          10.0                       R DE CHAMPEAUX   
242049   824490221     NaN         154.0                   RUE DU CHEMIN VERT   
242050   824526669     NaN          13.

In [4]:
df=df.astype({'postalCode': str, 'legalImmat': str, 'city':str})
df=df.drop(columns=["country","foundingYearSubs"],axis=1)
df['postalCode']=df['postalCode'].apply(lambda s: s[:5] if len(s)>=7 else '0'+s[:4])
df['dep']=df['postalCode'].str[:2]

##### On va le compléter par diveses informations : 
    - des informations géographiques sur la commune de localisation du restaurant : population, revenu moyen par habitant, informations touristiques
    - des informations internes au restaurant : capital social, prix moyen pratiqué, lien TripAdvisor, notes et avis reçus

### Informations géographiques

On récupére sur le site de l'INSEE un fichier recensant les communes et leur population : 

In [8]:
population_communes=pd.read_csv("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Communes.csv",sep=';',error_bad_lines= False, warn_bad_lines=True)

In [9]:
population_communes

DEPCOM                       COM    PMUN  PCAP    PTOT
0      01001  L' Abergement-Clémenciat     776    18     794
1      01002    L' Abergement-de-Varey     248     1     249
2      01004         Ambérieu-en-Bugey   14035   393   14428
3      01005       Ambérieux-en-Dombes    1689    34    1723
4      01006                   Ambléon     111     6     117
5      01007                  Ambronay    2726   115    2841
6      01008                  Ambutrix     752    15     767
7      01009          Andert-et-Condon     330     9     339
8      01010                 Anglefort    1115    17    1132
9      01011                  Apremont     376    11     387
10     01012                     Aranc     326     4     330
11     01013                   Arandas     144     4     148
12     01014                    Arbent    3367    92    3459
13     01016                   Arbigny     463     5     468
14     01015           Arboys en Bugey     644    17     661
15     01017                     Argis     442    16     458
16     01019                     Armix      28     1      29
17     01021           Ars-sur-Formans    1408    30    1438
18     01022                  Artemare    1237    18    1255
19     01453       Arvière-en-Valromey     713    22     735
20     01023        Asnières-sur-Saône      66     0      66
21     01024                  Attignat    3211    64    3275
22     01025            Bâgé-Dommartin    4092   108    4200
23     01026            Bâgé-le-Châtel     923    60     983
24     01027                     Balan    2684    57    2741
25     01028                   Baneins     602     9     611
26     01170        Béard-Géovreissiat    1051    28    1079
27     01029                  Beaupont     689     8     697
28     01030                Beauregard     866    14     880
29     01032                 Béligneux    3333    29    3362
...      ...                       ...     ...   ...     ...
34965  97310                     Roura    3783    59    3842
34966  97358                Saint-Élie     242     1     243
34967  97308             Saint-Georges    4131    89    4220
34968  97311   Saint-Laurent-du-Maroni   42612   324   42936
34969  97352                      Saül     152     8     160
34970  97312                 Sinnamary    2919    44    2963
34971  97401               Les Avirons   11345   166   11511
34972  97402                Bras-Panon   12811   181   12992
34973  97424                    Cilaos    5456    81    5537
34974  97403                Entre-Deux    6902    67    6969
34975  97404             L' Étang-Salé   13894   209   14103
34976  97405                Petite-Île   12162   111   12273
34977  97406   La Plaine-des-Palmistes    6565    94    6659
34978  97407                   Le Port   34128   310   34438
34979  97408             La Possession   33020   354   33374
34980  97409               Saint-André   56268   421   56689
34981  97410              Saint-Benoît   37759   254   38013
34982  97411               Saint-Denis  147931  1382  149313
34983  97412              Saint-Joseph   37644   522   38166
34984  97413                 Saint-Leu   33576   454   34030
34985  97414               Saint-Louis   53365   591   53956
34986  97415                Saint-Paul  104519  1368  105887
34987  97417            Saint-Philippe    5260    53    5313
34988  97416              Saint-Pierre   84212   871   85083
34989  97418              Sainte-Marie   33839   391   34230
34990  97419               Sainte-Rose    6418    79    6497
34991  97420            Sainte-Suzanne   23505   199   23704
34992  97421                   Salazie    7312    75    7387
34993  97422                 Le Tampon   78629  1076   79705
34994  97423         Les Trois-Bassins    7139    95    7234

[34995 rows x 5 columns]

In [10]:
population_communes=population_communes.rename(columns = {'DEPCOM': 'Code INSEE'})

Sur cette table, c'est le code INSEE qui est indiqué, (on a renommé juste au-dessus la variable DEPCOM en Code Insee) alors que sur notre table des restaurants, il s'agit du Code Postal. On ne peut donc pas directement faire la jointure ; il nous faut une table de correspondance entre code postal et Code Insee, qu'on récupère aussi sur le site de l'INSEE.

In [5]:
communes_insee=pd.read_csv("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/correspondance-code-insee-code-postal.csv",sep=';')

In [6]:
communes_insee

Code INSEE Code Postal                     Commune         Département  \
0          59276       59287                    GUESNAIN                NORD   
1          88128       88210                   DENIPAIRE              VOSGES   
2          57538       57170                 PETTONCOURT             MOSELLE   
3          54459       54630                RICHARDMENIL  MEURTHE-ET-MOSELLE   
4          35022       35190                    BECHEREL     ILLE-ET-VILAINE   
5          21459       21310             NOIRON-SUR-BEZE           COTE-D'OR   
6          33108       33350       CASTILLON-LA-BATAILLE             GIRONDE   
7          25088       25640                 BRECONCHAUX               DOUBS   
8          47120       47180                       JUSIX      LOT-ET-GARONNE   
9          39056       39140                  BLETTERANS                JURA   
10         51604       51140                    VENTELAY               MARNE   
11         25046       25380             BATTENANS-VARIN               DOUBS   
12         14674       14190                  SOIGNOLLES            CALVADOS   
13         21401       21190                    MELOISEY           COTE-D'OR   
14         61485       61120                  TICHEVILLE                ORNE   
15         63402       63550    SAINT-VICTOR-MONTVIANEIX         PUY-DE-DOME   
16         31153       31220                   COULADERE       HAUTE-GARONNE   
17         26027       26150                      BARSAC               DROME   
18         27567       27150  SAINTE-MARIE-DE-VATIMESNIL                EURE   
19         42205       42940    SAINT-BONNET-LE-COURREAU               LOIRE   
20         73057       73570            BRIDES-LES-BAINS              SAVOIE   
21         69063       69660      COLLONGES-AU-MONT-D'OR               RHONE   
22         46037       46330                     BOUZIES                 LOT   
23         61502       61360                       VIDAI                ORNE   
24         2A357       20116                     ZERUBIA        CORSE-DU-SUD   
25         68308       68290                     SICKERT           HAUT-RHIN   
26         42017       42660                   LE BESSAT               LOIRE   
27         27396       27850               MENESQUEVILLE                EURE   
28         74075       74270                      CHILLY        HAUTE-SAVOIE   
29         54013       54450                 AMENONCOURT  MEURTHE-ET-MOSELLE   
...          ...         ...                         ...                 ...   
36712      60589       60740               SAINT-MAXIMIN                OISE   
36713      14299       14600                  GENNEVILLE            CALVADOS   
36714      17118       17130                    CORIGNAC   CHARENTE-MARITIME   
36715      82177       82110                  SAUVETERRE     TARN-ET-GARONNE   
36716      17094       17340          CHATELAILLON-PLAGE   CHARENTE-MARITIME   
36717      68125       68210                      HECKEN           HAUT-RHIN   
36718      07269       07310     SAINT-MARTIN-DE-VALAMAS             ARDECHE   
36719      53104       53200           GENNES-SUR-GLAIZE             MAYENNE   
36720      03099       03240                DEUX-CHAISES              ALLIER   
36721      24368       24410        SAINT-ANTOINE-CUMOND            DORDOGNE   
36722      21659       21440                 VAUX-SAULES           COTE-D'OR   
36723      16119       16410                      DIGNAC            CHARENTE   
36724      95493       95270        LE PLESSIS-LUZARCHES          VAL-D'OISE   
36725      41178       41370        LE PLESSIS-L'ECHELLE        LOIR-ET-CHER   
36726      24061       24110                     BOURROU            DORDOGNE   
36727      21538       21530                SAINT-ANDEUX           COTE-D'OR   
36728      57058       57460          BEHREN-LES-FORBACH             MOSELLE   
36729      51448       51140                    PROUILLY               MARNE   
36730 

In [7]:
corresp=communes_insee.drop(columns=['geo_point_2d','geo_shape','ID Geofla','Code Commune','Code Canton','Code Arrondissement','Code Région','Code Département','Statut'],axis=1)

On peut faire la jointure entre nos deux tables population et correspondance code INSEE, code Postal (clé commune = Code INSEE) :

In [11]:
pop_superf=pd.merge(corresp,population_communes)
pop_superf=pop_superf.drop(columns=['COM','PMUN','PCAP','Population'],axis=1)

Notre nouvelle table pop_superf contient désormais de nombreuses informations géographiques sur les communes : altitude, superficie, et surtout population.

In [12]:
pop_superf

Code INSEE Code Postal                     Commune         Département  \
0          59276       59287                    GUESNAIN                NORD   
1          88128       88210                   DENIPAIRE              VOSGES   
2          57538       57170                 PETTONCOURT             MOSELLE   
3          54459       54630                RICHARDMENIL  MEURTHE-ET-MOSELLE   
4          35022       35190                    BECHEREL     ILLE-ET-VILAINE   
5          21459       21310             NOIRON-SUR-BEZE           COTE-D'OR   
6          33108       33350       CASTILLON-LA-BATAILLE             GIRONDE   
7          25088       25640                 BRECONCHAUX               DOUBS   
8          47120       47180                       JUSIX      LOT-ET-GARONNE   
9          39056       39140                  BLETTERANS                JURA   
10         51604       51140                    VENTELAY               MARNE   
11         25046       25380             BATTENANS-VARIN               DOUBS   
12         14674       14190                  SOIGNOLLES            CALVADOS   
13         21401       21190                    MELOISEY           COTE-D'OR   
14         61485       61120                  TICHEVILLE                ORNE   
15         63402       63550    SAINT-VICTOR-MONTVIANEIX         PUY-DE-DOME   
16         31153       31220                   COULADERE       HAUTE-GARONNE   
17         26027       26150                      BARSAC               DROME   
18         27567       27150  SAINTE-MARIE-DE-VATIMESNIL                EURE   
19         42205       42940    SAINT-BONNET-LE-COURREAU               LOIRE   
20         73057       73570            BRIDES-LES-BAINS              SAVOIE   
21         69063       69660      COLLONGES-AU-MONT-D'OR               RHONE   
22         46037       46330                     BOUZIES                 LOT   
23         61502       61360                       VIDAI                ORNE   
24         2A357       20116                     ZERUBIA        CORSE-DU-SUD   
25         68308       68290                     SICKERT           HAUT-RHIN   
26         42017       42660                   LE BESSAT               LOIRE   
27         27396       27850               MENESQUEVILLE                EURE   
28         74075       74270                      CHILLY        HAUTE-SAVOIE   
29         54013       54450                 AMENONCOURT  MEURTHE-ET-MOSELLE   
...          ...         ...                         ...                 ...   
34962      14273       14290        LA FOLLETIERE-ABENON            CALVADOS   
34963      60539       60870                       RIEUX                OISE   
34964      60589       60740               SAINT-MAXIMIN                OISE   
34965      14299       14600                  GENNEVILLE            CALVADOS   
34966      17118       17130                    CORIGNAC   CHARENTE-MARITIME   
34967      82177       82110                  SAUVETERRE     TARN-ET-GARONNE   
34968      17094       17340          CHATELAILLON-PLAGE   CHARENTE-MARITIME   
34969      68125       68210                      HECKEN           HAUT-RHIN   
34970      07269       07310     SAINT-MARTIN-DE-VALAMAS             ARDECHE   
34971      53104       53200           GENNES-SUR-GLAIZE             MAYENNE   
34972      03099       03240                DEUX-CHAISES              ALLIER   
34973      21659       21440                 VAUX-SAULES           COTE-D'OR   
34974      16119       16410                      DIGNAC            CHARENTE   
34975      95493       95270        LE PLESSIS-LUZARCHES          VAL-D'OISE   
34976      41178       41370        LE PLESSIS-L'ECHELLE        LOIR-ET-CHER   
34977      24061       24110                     BOURROU            DORDOGNE   
34978      21538       21530                SAINT-ANDEUX           COTE-D'OR   
34979      57058       57460          BEHREN-LES-FORBACH             MOSELLE   
34980 

Il nous faut maintenant des informations sur le niveau de vie des communes : on récupère un fichier csv de l'INSEE qui indique pour chaque commune son "niveau de vie" = revenu moyen par habitant.

In [14]:
revenus_com=pd.read_excel("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Niveau_de_vie_2013_a_la_commune-Global_Map_Solution.xlsx")

In [15]:
revenus_com

Code Commune                  Nom Commune  Niveau de vie Commune  \
0            05047                      Éourres           10021.250000   
1            26142                     Glandage           10215.000000   
2            11317                       Rodome           10908.500000   
3            11384                     Soulatgé           11485.166667   
4            30153               Malons-et-Elze           11680.000000   
5            13203  Marseille 3e Arrondissement           11760.800000   
6            26055                        Boulc           11903.214286   
7            09118              Esplas-de-Sérou           12074.000000   
8            11346        Saint-Jean-de-Paracol           12173.333333   
9            09231                      Le Port           12193.000000   
10           11142        Festes-et-Saint-André           12239.375000   
11           09009                        Alzen           12424.285714   
12           48171    Saint-Martin-de-Lansuscle           12574.000000   
13           30296      Saint-Roman-de-Codières           12609.523810   
14           26361                     Valdrôme           12695.517241   
15           07147        Malarce-sur-la-Thines           12702.000000   
16           23178      Saint-Agnant-près-Crocq           12706.600000   
17           11191                Laroque-de-Fa           12745.000000   
18           11260                   Mouthoumet           12827.500000   
19           15112                        Malbo           12836.666667   
20           11117                     Davejean           12866.190476   
21           93014             Clichy-sous-Bois           12866.521739   
22           30246      Sainte-Croix-de-Caderle           12867.333333   
23           24039                        Besse           12893.000000   
24           09057                        Biert           12902.380952   
25           34158                      Minerve           12919.761905   
26           91286                       Grigny           12933.809524   
27           26356                      Truinas           12934.153846   
28           12035                        Brasc           12991.820513   
29           11044                      Bouisse           13001.000000   
...            ...                          ...                    ...   
36542        68190                      Lucelle                    NaN   
36543        68293                  Saint-Cosme                    NaN   
36544        77200                Garentreville                    NaN   
36545        77304                    Montenils                    NaN   
36546        77342                   Obsonville                    NaN   
36547        77356              Passy-sur-Seine                    NaN   
36548        77452                         Sigy                    NaN   
36549        77532         Vulaines-lès-Provins                    NaN   
36550        01019                        Armix                    NaN   
36551        01023           Asnières-sur-Saône                    NaN   
36552        01051                      Bolozon                    NaN   
36553        01059                       Brénaz                    NaN   
36554        01162                      Flaxieu                    NaN   
36555        01186                      Hostiaz                    NaN   
36556        01190                     Innimond                    NaN   
36557        01066                 La Burbanche                    NaN   
36558        01215                     Lhôpital                    NaN   
36559        01218                      Lochieu                    NaN   
36560        01279                       Oncieu                    NaN   
36561        01309                     Pouillat                    NaN   
36562        01311                   Prémillieu                    NaN   
36563        01413                      Surjoux                    NaN   
36564     

In [16]:
revenus_com=revenus_com.rename(columns={'Code Commune':'Code INSEE'})

On joint cette table à notre dataframe précédent pop_superf (clé commune = Code INSEE toujours). On obtient un dataframe plus complet, nommé intemed.

In [17]:
intemed=pd.merge(pop_superf,revenus_com,how='left')
intemed=intemed.drop(columns=['Nom Commune'],axis=1)

In [18]:
intemed

Code INSEE Code Postal                     Commune         Département  \
0          59276       59287                    GUESNAIN                NORD   
1          88128       88210                   DENIPAIRE              VOSGES   
2          57538       57170                 PETTONCOURT             MOSELLE   
3          54459       54630                RICHARDMENIL  MEURTHE-ET-MOSELLE   
4          35022       35190                    BECHEREL     ILLE-ET-VILAINE   
5          21459       21310             NOIRON-SUR-BEZE           COTE-D'OR   
6          33108       33350       CASTILLON-LA-BATAILLE             GIRONDE   
7          25088       25640                 BRECONCHAUX               DOUBS   
8          47120       47180                       JUSIX      LOT-ET-GARONNE   
9          39056       39140                  BLETTERANS                JURA   
10         51604       51140                    VENTELAY               MARNE   
11         25046       25380             BATTENANS-VARIN               DOUBS   
12         14674       14190                  SOIGNOLLES            CALVADOS   
13         21401       21190                    MELOISEY           COTE-D'OR   
14         61485       61120                  TICHEVILLE                ORNE   
15         63402       63550    SAINT-VICTOR-MONTVIANEIX         PUY-DE-DOME   
16         31153       31220                   COULADERE       HAUTE-GARONNE   
17         26027       26150                      BARSAC               DROME   
18         27567       27150  SAINTE-MARIE-DE-VATIMESNIL                EURE   
19         42205       42940    SAINT-BONNET-LE-COURREAU               LOIRE   
20         73057       73570            BRIDES-LES-BAINS              SAVOIE   
21         69063       69660      COLLONGES-AU-MONT-D'OR               RHONE   
22         46037       46330                     BOUZIES                 LOT   
23         61502       61360                       VIDAI                ORNE   
24         2A357       20116                     ZERUBIA        CORSE-DU-SUD   
25         68308       68290                     SICKERT           HAUT-RHIN   
26         42017       42660                   LE BESSAT               LOIRE   
27         27396       27850               MENESQUEVILLE                EURE   
28         74075       74270                      CHILLY        HAUTE-SAVOIE   
29         54013       54450                 AMENONCOURT  MEURTHE-ET-MOSELLE   
...          ...         ...                         ...                 ...   
34962      14273       14290        LA FOLLETIERE-ABENON            CALVADOS   
34963      60539       60870                       RIEUX                OISE   
34964      60589       60740               SAINT-MAXIMIN                OISE   
34965      14299       14600                  GENNEVILLE            CALVADOS   
34966      17118       17130                    CORIGNAC   CHARENTE-MARITIME   
34967      82177       82110                  SAUVETERRE     TARN-ET-GARONNE   
34968      17094       17340          CHATELAILLON-PLAGE   CHARENTE-MARITIME   
34969      68125       68210                      HECKEN           HAUT-RHIN   
34970      07269       07310     SAINT-MARTIN-DE-VALAMAS             ARDECHE   
34971      53104       53200           GENNES-SUR-GLAIZE             MAYENNE   
34972      03099       03240                DEUX-CHAISES              ALLIER   
34973      21659       21440                 VAUX-SAULES           COTE-D'OR   
34974      16119       16410                      DIGNAC            CHARENTE   
34975      95493       95270        LE PLESSIS-LUZARCHES          VAL-D'OISE   
34976      41178       41370        LE PLESSIS-L'ECHELLE        LOIR-ET-CHER   
34977      24061       24110                     BOURROU            DORDOGNE   
34978      21538       21530                SAINT-ANDEUX           COTE-D'OR   
34979      57058       57460          BEHREN-LES-FORBACH             MOSELLE   
34980 

Enfin, on souhaite récupérer des informations touristiques sur nos communes, car on pense bien qu'un restaurant situé dans des communes plus touristiques que d'autres est à même de pratiquer des prix plus élevés.

On récupère un fichier excel, toujours sur le site de l'INSEE

In [19]:
tourist_communes=pd.ExcelFile("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/base-cc-tourisme-2020.xlsx")

Ce fichier est assez dense, contient 4 feuilles excel différentes comme on peut le voir juste en-dessous. Seul nous intéresse les deux premières feuille excel : 'COM', qui contient les données recherchées pour les communes, et 'ARM', qui contient les mêmes données mais pour les arrondissements des 3 plus grandes villes (Lyon/Paris/Marseille).

In [20]:
print(tourist_communes.sheet_names)

['COM', 'ARM', 'Variables', 'Documentation']


In [21]:
communes_touristiques=pd.read_excel(tourist_communes,'COM',header=5)
arrondissements_touristiques=pd.read_excel(tourist_communes,'ARM',header=5)

In [22]:
arrondissements_touristiques=arrondissements_touristiques.astype({'CODGEO': str})

In [23]:
tourisme=pd.concat([communes_touristiques,arrondissements_touristiques])

In [24]:
keep_col=['CODGEO','LIBGEO','HT20','HT120','HT220','HT320','HT420','HT520','CPG20','RT20']
tourisme = tourisme[[c for c in tourisme.columns if c in keep_col]]
tourisme=tourisme.rename(columns={'CODGEO':'Code INSEE'})

##### On ne garde que les principales variables touristiques qui vont nous intéresser, à savoir : 
    - HT20 : nombre d'hôtels dans la commune en question en 2020
    - HT120 : nombre d'hôtels 1 étoile dans la commune en 2020
    - HT220 : nombre d'hôtels 2 étoiles
        ...
        
    - CPG20 : nombre de campings dans la commune en 2020
    - RT20 : nombre de résidence de tourisme et hébergements assimilés dans la commune en 2020

In [25]:
tourisme

Code INSEE                        LIBGEO   HT20  HT120  HT220  HT320  \
0       01001       L'Abergement-Clémenciat    0.0    0.0    0.0    0.0   
1       01002         L'Abergement-de-Varey    0.0    0.0    0.0    0.0   
2       01004             Ambérieu-en-Bugey    1.0    0.0    0.0    1.0   
3       01005           Ambérieux-en-Dombes    2.0    0.0    0.0    1.0   
4       01006                       Ambléon    0.0    0.0    0.0    0.0   
5       01007                      Ambronay    0.0    0.0    0.0    0.0   
6       01008                      Ambutrix    0.0    0.0    0.0    0.0   
7       01009              Andert-et-Condon    0.0    0.0    0.0    0.0   
8       01010                     Anglefort    1.0    0.0    0.0    0.0   
9       01011                      Apremont    0.0    0.0    0.0    0.0   
10      01012                         Aranc    1.0    0.0    0.0    1.0   
11      01013                       Arandas    0.0    0.0    0.0    0.0   
12      01014                        Arbent    1.0    0.0    1.0    0.0   
13      01015               Arboys en Bugey    0.0    0.0    0.0    0.0   
14      01016                       Arbigny    1.0    0.0    0.0    1.0   
15      01017                         Argis    0.0    0.0    0.0    0.0   
16      01019                         Armix    0.0    0.0    0.0    0.0   
17      01021               Ars-sur-Formans    1.0    0.0    1.0    0.0   
18      01022                      Artemare    0.0    0.0    0.0    0.0   
19      01023            Asnières-sur-Saône    0.0    0.0    0.0    0.0   
20      01024                      Attignat    1.0    0.0    1.0    0.0   
21      01025                Bâgé-Dommartin    0.0    0.0    0.0    0.0   
22      01026                Bâgé-le-Châtel    0.0    0.0    0.0    0.0   
23      01027                         Balan    0.0    0.0    0.0    0.0   
24      01028                       Baneins    0.0    0.0    0.0    0.0   
25      01029                      Beaupont    0.0    0.0    0.0    0.0   
26      01030                    Beauregard    0.0    0.0    0.0    0.0   
27      01031                     Bellignat    1.0    0.0    1.0    0.0   
28      01032                     Béligneux    0.0    0.0    0.0    0.0   
29      01033                    Valserhône    6.0    0.0    2.0    1.0   
..        ...                           ...    ...    ...    ...    ...   
15      13216  Marseille 16e Arrondissement    2.0    0.0    2.0    0.0   
16      69381       Lyon 1er Arrondissement    6.0    0.0    3.0    1.0   
17      69382        Lyon 2e Arrondissement   51.0    1.0   14.0   16.0   
18      69383        Lyon 3e Arrondissement   17.0    0.0    3.0    6.0   
19      69384        Lyon 4e Arrondissement    3.0    0.0    1.0    1.0   
20      69385        Lyon 5e Arrondissement    8.0    0.0    0.0    1.0   
21      69386        Lyon 6e Arrondissement   12.0    0.0    1.0    4.0   
22      69387        Lyon 7e Arrondissement   10.0    1.0    2.0    5.0   
23      69388        Lyon 8e Arrondissement    3.0    0.0    2.0    1.0   
24      69389        Lyon 9e Arrondissement    3.0    0.0    0.0    3.0   
25      75101      Paris 1er Arrondissement   74.0    1.0    4.0   21.0   
26      75102       Paris 2e Arrondissement   48.0    0.0    1.0   15.0   
27      75103       Paris 3e Arrondissement   31.0    0.0    4.0    9.0   
28      75104       Paris 4e Arrondissement   37.0    1.0    3.0   20.0   
29      75105       Paris 5e Arrondissement   84.0    1.0   14.0   35.0   
30      75106       Paris 6e Arrondissement  105.0    1.0   10.0   40.0   
31      75107       Paris 7e Arrondissement   65.0    0.0    4.0   27.0   
32      75108       Paris 8e Arrondissement  152.0    1.0    5.0   39.0   
33      75109       Paris 9e Arrondissement  182.0    0.0   16.0   89.0   
34      75110      Paris 10e Arrondissement  120.0    0.0   22.0   50.0   
35      75111      Paris 11e Arrondissement   74.0    1.0   12.0   33.0   
36      75112      Paris 12e

On joint cette table à la précédente, toujours sur la clé commune Code INSEE

In [26]:
donnees_externes=pd.merge(intemed,tourisme)

On a désormais toute une table complète de données géographiques contenant diverses informations sur les communes

In [27]:
donnees_externes

Code INSEE Code Postal                     Commune         Département  \
0          59276       59287                    GUESNAIN                NORD   
1          88128       88210                   DENIPAIRE              VOSGES   
2          57538       57170                 PETTONCOURT             MOSELLE   
3          54459       54630                RICHARDMENIL  MEURTHE-ET-MOSELLE   
4          35022       35190                    BECHEREL     ILLE-ET-VILAINE   
5          21459       21310             NOIRON-SUR-BEZE           COTE-D'OR   
6          33108       33350       CASTILLON-LA-BATAILLE             GIRONDE   
7          25088       25640                 BRECONCHAUX               DOUBS   
8          47120       47180                       JUSIX      LOT-ET-GARONNE   
9          39056       39140                  BLETTERANS                JURA   
10         51604       51140                    VENTELAY               MARNE   
11         25046       25380             BATTENANS-VARIN               DOUBS   
12         14674       14190                  SOIGNOLLES            CALVADOS   
13         21401       21190                    MELOISEY           COTE-D'OR   
14         61485       61120                  TICHEVILLE                ORNE   
15         63402       63550    SAINT-VICTOR-MONTVIANEIX         PUY-DE-DOME   
16         31153       31220                   COULADERE       HAUTE-GARONNE   
17         26027       26150                      BARSAC               DROME   
18         27567       27150  SAINTE-MARIE-DE-VATIMESNIL                EURE   
19         42205       42940    SAINT-BONNET-LE-COURREAU               LOIRE   
20         73057       73570            BRIDES-LES-BAINS              SAVOIE   
21         69063       69660      COLLONGES-AU-MONT-D'OR               RHONE   
22         46037       46330                     BOUZIES                 LOT   
23         61502       61360                       VIDAI                ORNE   
24         2A357       20116                     ZERUBIA        CORSE-DU-SUD   
25         68308       68290                     SICKERT           HAUT-RHIN   
26         42017       42660                   LE BESSAT               LOIRE   
27         27396       27850               MENESQUEVILLE                EURE   
28         74075       74270                      CHILLY        HAUTE-SAVOIE   
29         54013       54450                 AMENONCOURT  MEURTHE-ET-MOSELLE   
...          ...         ...                         ...                 ...   
34959      14273       14290        LA FOLLETIERE-ABENON            CALVADOS   
34960      60539       60870                       RIEUX                OISE   
34961      60589       60740               SAINT-MAXIMIN                OISE   
34962      14299       14600                  GENNEVILLE            CALVADOS   
34963      17118       17130                    CORIGNAC   CHARENTE-MARITIME   
34964      82177       82110                  SAUVETERRE     TARN-ET-GARONNE   
34965      17094       17340          CHATELAILLON-PLAGE   CHARENTE-MARITIME   
34966      68125       68210                      HECKEN           HAUT-RHIN   
34967      07269       07310     SAINT-MARTIN-DE-VALAMAS             ARDECHE   
34968      53104       53200           GENNES-SUR-GLAIZE             MAYENNE   
34969      03099       03240                DEUX-CHAISES              ALLIER   
34970      21659       21440                 VAUX-SAULES           COTE-D'OR   
34971      16119       16410                      DIGNAC            CHARENTE   
34972      95493       95270        LE PLESSIS-LUZARCHES          VAL-D'OISE   
34973      41178       41370        LE PLESSIS-L'ECHELLE        LOIR-ET-CHER   
34974      24061       24110                     BOURROU            DORDOGNE   
34975      21538       21530                SAINT-ANDEUX           COTE-D'OR   
34976      57058       57460          BEHREN-LES-FORBACH             MOSELLE   
34977 

In [28]:
donnees_externes=donnees_externes.drop(columns=['LIBGEO'],axis=1)

Maintenant, on joint les donnees_externes à df :
la colonne commune est le code postal

In [29]:
df=df.rename(columns={'postalCode': 'Code Postal'})

In [30]:
df

legalImmat  streetNumber                           streetName  \
0         7340516           NaN                                  NaN   
1        46412375          21.0                    RUE GEN DE GAULLE   
2        66304932           NaN                   COLLEGE DE KOUNGOU   
3        76912112           NaN                              LE COIN   
4       300443124           NaN               LIEU-DIT CAVALLO MORTO   
5       301341517           1.0                 ESPLANADE PARMENTIER   
6       301863668           NaN                     BOIS DE COULANGE   
7       302296629         146.0                      RUE ROBESPIERRE   
8       303406540           9.0                 AVENUE DE STALINGRAD   
9       303797823           NaN                  LA MARE AUX PRETRES   
10      304305519           5.0                      AVENUE DU MAINE   
11      305021909          19.0                    RUE DE LA CHARITE   
12      305426454          23.0                  RUE MARECHAL JOFFRE   
13      305836033           NaN                    CHEMIN DE LA LONE   
14      305836033           NaN                  ROUTE DE BAR LE DUC   
15      305836033          43.0                       RUE DU PLATEAU   
16      306126210           NaN                LIEU-DIT GERBIER JONC   
17      306332362          25.0                   RUE DE LA HUCHETTE   
18      306999137          27.0                      RUE DE NOAILLES   
19      307711895          15.0                      PLACE DU TERTRE   
20      308880228         361.0                  AVENUE DU 15E CORPS   
21      309408797           1.0                         RUE MAUSSIRE   
22      309654457         113.0              RUE DU MARECHAL LECLERC   
23      310187562           NaN                     ALLEE RAY GRASSI   
24      310727979           NaN               LIEU-DIT LA MARIAUDAIS   
25      311160592          30.0                COURS DE L'ILE SEGUIN   
26      311372569           NaN                         LES PLATANES   
27      311970552          13.0                  RUE DES BAS SABLONS   
28      312274426          22.0                      ROUTE IMPERIALE   
29      312732837           2.0                   PLACE JEANNE D'ARC   
...           ...           ...                                  ...   
242033  824097901           NaN                    RUE DE LA STATION   
242034  824121123           6.0                   RUE DES SERRURIERS   
242035  824145874           2.0                          R DES CAVES   
242036  824170633          49.0                      RUE JEAN MOULIN   
242037  824195283          11.0              CHEMIN DU PETIT CASTERA   
242038  824211098          28.0                          RUE BLANQUI   
242039  824240980          30.0              BOULEVARD DE SEBASTOPOL   
242040  824260178         308.0                     RUE ALBERT CAMUS   
242041  824277594          23.0                  RUE NICOLAS BOILEAU   
242042  824313852           4.0                     BOULEVARD GIRAUD   
242043  824340020          12.0                          RUE LAKANAL   
242044  824352777         243.0                 AVENUE DE VILLENEUVE   
242045  824374318          13.0                         R DE VIGNORU   
242046  824401830          55.0                  RUE DU GENERAL BUAT   
242047  824429237          12.0                         RUE DE DREUX   
242048  824462725          10.0                       R DE CHAMPEAUX   
242049  824490221         154.0                   RUE DU CHEMIN VERT   
242050  824526669          13.0                   AVENUE JEAN JAURES   
242051  824557607           3.0                          RUE BOUGEAU   
242052  824585665          17.0             BOULEVARD AMIRAL COURBET   
242053  824619936          46.0                      PLACE DU TRIPOT   
242054  947151684           NaN                    LIEU-DIT LANGMATT   
242055  950026914           1.0             BOULEVARD AMIRAL COURBET   
242056  950026914           1.0                

In [32]:
etablissements=pd.merge(df,donnees_externes,how='left')

In [33]:
etablissements

legalImmat  streetNumber                           streetName  \
0         7340516           NaN                                  NaN   
1         7340516           NaN                                  NaN   
2         7340516           NaN                                  NaN   
3         7340516           NaN                                  NaN   
4         7340516           NaN                                  NaN   
5         7340516           NaN                                  NaN   
6         7340516           NaN                                  NaN   
7         7340516           NaN                                  NaN   
8         7340516           NaN                                  NaN   
9         7340516           NaN                                  NaN   
10        7340516           NaN                                  NaN   
11        7340516           NaN                                  NaN   
12       46412375          21.0                    RUE GEN DE GAULLE   
13       46412375          21.0                    RUE GEN DE GAULLE   
14       46412375          21.0                    RUE GEN DE GAULLE   
15       46412375          21.0                    RUE GEN DE GAULLE   
16       66304932           NaN                   COLLEGE DE KOUNGOU   
17       76912112           NaN                              LE COIN   
18      300443124           NaN               LIEU-DIT CAVALLO MORTO   
19      301341517           1.0                 ESPLANADE PARMENTIER   
20      301341517           1.0                 ESPLANADE PARMENTIER   
21      301863668           NaN                     BOIS DE COULANGE   
22      302296629         146.0                      RUE ROBESPIERRE   
23      303406540           9.0                 AVENUE DE STALINGRAD   
24      303797823           NaN                  LA MARE AUX PRETRES   
25      303797823           NaN                  LA MARE AUX PRETRES   
26      303797823           NaN                  LA MARE AUX PRETRES   
27      303797823           NaN                  LA MARE AUX PRETRES   
28      303797823           NaN                  LA MARE AUX PRETRES   
29      303797823           NaN                  LA MARE AUX PRETRES   
...           ...           ...                                  ...   
956978  824619936          46.0                      PLACE DU TRIPOT   
956979  824619936          46.0                      PLACE DU TRIPOT   
956980  824619936          46.0                      PLACE DU TRIPOT   
956981  824619936          46.0                      PLACE DU TRIPOT   
956982  824619936          46.0                      PLACE DU TRIPOT   
956983  824619936          46.0                      PLACE DU TRIPOT   
956984  824619936          46.0                      PLACE DU TRIPOT   
956985  824619936          46.0                      PLACE DU TRIPOT   
956986  947151684           NaN                    LIEU-DIT LANGMATT   
956987  947151684           NaN                    LIEU-DIT LANGMATT   
956988  950026914           1.0             BOULEVARD AMIRAL COURBET   
956989  950026914           1.0                      RUE JEAN JAURES   
956990  950026914         435.0              ZONE INDUST DE COURTINE   
956991  950026914           NaN                        ROUTE DE SETE   
956992  950026914           NaN  RUE DE L'EGALITE LIEUDIT LE BAS DES   
956993  950375642           NaN                  ALLEE DE LA JOCONDE   
956994  950375642           NaN                  ALLEE DE LA JOCONDE   
956995  950375642           NaN                  ALLEE DE LA JOCONDE   
956996  950375642           NaN                  ALLEE DE LA JOCONDE   
956997  950375642           NaN                  ALLEE DE LA JOCONDE   
956998  950375642           NaN                  ALLEE DE LA JOCONDE   
956999  950375642           NaN                  ALLEE DE LA JOCONDE   
957000  950375642           NaN                  ALLEE DE LA JOCONDE   
957001  950375642           NaN                

Probleme ! Car un code postal correspond à plusieurs communes, alors que le Code Insee correspond à une seule commune.
Par conséquent, on se trouve dans une table avec des numéros de siren répétés, car le code postal du restaurant correspondant est répété autant de fois qu'il existe de numéros insee ayant ce code postal


Illustration avec l'entreprise de siren ' 7340516 ' :


In [34]:
etablissements[etablissements['legalImmat']=='7340516']


legalImmat  streetNumber streetName Code Postal        city  \
0     7340516           NaN        NaN       04250  CLAMENSANE   
1     7340516           NaN        NaN       04250  CLAMENSANE   
2     7340516           NaN        NaN       04250  CLAMENSANE   
3     7340516           NaN        NaN       04250  CLAMENSANE   
4     7340516           NaN        NaN       04250  CLAMENSANE   
5     7340516           NaN        NaN       04250  CLAMENSANE   
6     7340516           NaN        NaN       04250  CLAMENSANE   
7     7340516           NaN        NaN       04250  CLAMENSANE   
8     7340516           NaN        NaN       04250  CLAMENSANE   
9     7340516           NaN        NaN       04250  CLAMENSANE   
10    7340516           NaN        NaN       04250  CLAMENSANE   
11    7340516           NaN        NaN       04250  CLAMENSANE   

    isHeadquarters categoryType        legalName contactName contactFirstname  \
0                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
1                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
2                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
3                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
4                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
5                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
6                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
7                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
8                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
9                1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
10               1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   
11               1   Commerçant  ROUX*MEGY/AIME/        ROUX             AIME   

    ... Niveau de vie Commune Niveau de vie Département HT20  HT120  HT220  \
0   ...                   NaN              19008.420673  0.0    0.0    0.0   
1   ...                   NaN              19008.420673  0.0    0.0    0.0   
2   ...          16323.333333              19008.420673  0.0    0.0    0.0   
3   ...          18580.000000              19008.420673  0.0    0.0    0.0   
4   ...          16936.666667              19008.420673  0.0    0.0    0.0   
5   ...          18083.452381              19008.420673  0.0    0.0    0.0   
6   ...                   NaN              19008.420673  0.0    0.0    0.0   
7   ...                   NaN              19008.420673  0.0    0.0    0.0   
8   ...                   NaN              19008.420673  0.0    0.0    0.0   
9   ...                   NaN              19008.420673  0.0    0.0    0.0   
10  ...          17738.571429              19008.420673  0.0    0.0    0.0   
11  ...          17544.130952              19008.420673  0.0    0.0    0.0   

   HT320  HT420 HT520 CPG20  RT20  
0    0.0    0.0   0.0   0.0   0.0  
1    0.0    0.0   0.0   1.0   0.0  
2    0.0    0.0   0.0   0.0   0.0  
3    0.0    0.0   0.0   0.0   0.0  
4    0.0    0.0   0.0   0.0   0.0  
5    0.0    0.0   0.0   2.0   0.0  
6    0.0    0.0   0.0   0.0   0.0  
7    0.0    0.0   0.0   0.0   0.0  
8    0.0    0.0   0.0   0.0   0.0  
9    0.0    0.0   0.0   0.0   0.0  
10   0.0    0.0   0.0   2.0   0.0  
11   0.0    0.0   0.0   0.0   0.0  

[12 rows x 41 columns]

Ici, il y 12 lignes pour le même établissement, car le code postal "04250" correspond à 12 communes différentes :

In [35]:
etablissements[etablissements['legalImmat']=='7340516']['Commune']

0              LE CAIRE
1                GIGORS
2                BAYONS
3           BELLAFFAIRE
4              TURRIERS
5            CLAMENSANE
6           CHATEAUFORT
7             VALAVOIRE
8                NIBLES
9       FAUCON-DU-CAIRE
10    LA MOTTE-DU-CAIRE
11                MELVE
Name: Commune, dtype: object

 Notre établissement est situé dans la commune de "CLAMENSANE" ; il faut donc choisir la bonne ligne parmi les douzes, c'est-à-dire celle qui correspond à "CLAMENSANE"
 
 Le plus simple est de refaire la jointure entre df et donnees_exterieures, en rajoutant la condition "même nom de commune" (le nom de la commune étant présent dans les deux tables qu'on veut joindre). Cependant, et puisque certains noms de communes posent problème avec des tirets dans une table et non présents dans l'autre, on va dans chaque table créer la variabe id_nom qui transforme le nom de la commune en une suite de caractères collés (c'est-à-dire on supprime les espaces, apostrophes ou tirets).

Si on tombe sur un arrondissement de Paris, Lyon ou Marseille, la variable prend le code postal comme valeur (en fait ces trois villes ne posent pas problème pour la jointure car il y a un unique code postal pour chaque arrondissement de ces villes). cependant, on ne leur applique pas le même traitement que les autres (à savoir supprimer espaces, tirets, apostrophes), car dans la table df, leur nom est du type "Paris5", alors que dans la table donnees_externes, leur nom est du type "Paris5EArrondissement", ce qui nécessiterait de faire encore d'autres opérations inutiles pour avoir les mêmes noms 
 
 
 

In [36]:
# liste des codes Postaux des arrondissements de nos trois villes

liste_code=['75001','75002','75003','75004','75005','75006','75007','75008','75009','75010',
           '75011','75012','75013','75014','75015','75016','75017','75018','75019','75020',
           '69001','69002','69003','69004','69005','69006','69007','69008','69009','13001',
          '13002','13003','13004','13005','13006','13007','13008','13009','13010','13011',
          '13012','13013','13014','13015','13016']

donnees_externes['id_nom']=donnees_externes.apply(lambda s: re.sub('[-\'\s]','',s['Commune']) if s['Code Postal'] not in liste_code else s['Code Postal'],axis=1)

df['id_nom']=df.apply(lambda s: re.sub('[-\'\s]','',s['city']) if s['Code Postal'] not in liste_code else s['Code Postal'],axis=1)


On peut désormais faire notre jointure de df et donnees_externes : celle-ci se fera sur les deux colonnes communes code_postal et id_nom


In [37]:
etablissements=pd.merge(df,donnees_externes,how='left')

In [39]:
etablissements

legalImmat  streetNumber                           streetName  \
0         7340516           NaN                                  NaN   
1        46412375          21.0                    RUE GEN DE GAULLE   
2        66304932           NaN                   COLLEGE DE KOUNGOU   
3        76912112           NaN                              LE COIN   
4       300443124           NaN               LIEU-DIT CAVALLO MORTO   
5       301341517           1.0                 ESPLANADE PARMENTIER   
6       301863668           NaN                     BOIS DE COULANGE   
7       302296629         146.0                      RUE ROBESPIERRE   
8       303406540           9.0                 AVENUE DE STALINGRAD   
9       303797823           NaN                  LA MARE AUX PRETRES   
10      304305519           5.0                      AVENUE DU MAINE   
11      305021909          19.0                    RUE DE LA CHARITE   
12      305426454          23.0                  RUE MARECHAL JOFFRE   
13      305836033           NaN                    CHEMIN DE LA LONE   
14      305836033           NaN                  ROUTE DE BAR LE DUC   
15      305836033          43.0                       RUE DU PLATEAU   
16      306126210           NaN                LIEU-DIT GERBIER JONC   
17      306332362          25.0                   RUE DE LA HUCHETTE   
18      306999137          27.0                      RUE DE NOAILLES   
19      307711895          15.0                      PLACE DU TERTRE   
20      308880228         361.0                  AVENUE DU 15E CORPS   
21      309408797           1.0                         RUE MAUSSIRE   
22      309654457         113.0              RUE DU MARECHAL LECLERC   
23      310187562           NaN                     ALLEE RAY GRASSI   
24      310727979           NaN               LIEU-DIT LA MARIAUDAIS   
25      311160592          30.0                COURS DE L'ILE SEGUIN   
26      311372569           NaN                         LES PLATANES   
27      311970552          13.0                  RUE DES BAS SABLONS   
28      312274426          22.0                      ROUTE IMPERIALE   
29      312732837           2.0                   PLACE JEANNE D'ARC   
...           ...           ...                                  ...   
242035  824097901           NaN                    RUE DE LA STATION   
242036  824121123           6.0                   RUE DES SERRURIERS   
242037  824145874           2.0                          R DES CAVES   
242038  824170633          49.0                      RUE JEAN MOULIN   
242039  824195283          11.0              CHEMIN DU PETIT CASTERA   
242040  824211098          28.0                          RUE BLANQUI   
242041  824240980          30.0              BOULEVARD DE SEBASTOPOL   
242042  824260178         308.0                     RUE ALBERT CAMUS   
242043  824277594          23.0                  RUE NICOLAS BOILEAU   
242044  824313852           4.0                     BOULEVARD GIRAUD   
242045  824340020          12.0                          RUE LAKANAL   
242046  824352777         243.0                 AVENUE DE VILLENEUVE   
242047  824374318          13.0                         R DE VIGNORU   
242048  824401830          55.0                  RUE DU GENERAL BUAT   
242049  824429237          12.0                         RUE DE DREUX   
242050  824462725          10.0                       R DE CHAMPEAUX   
242051  824490221         154.0                   RUE DU CHEMIN VERT   
242052  824526669          13.0                   AVENUE JEAN JAURES   
242053  824557607           3.0                          RUE BOUGEAU   
242054  824585665          17.0             BOULEVARD AMIRAL COURBET   
242055  824619936          46.0                      PLACE DU TRIPOT   
242056  947151684           NaN                    LIEU-DIT LANGMATT   
242057  950026914           1.0             BOULEVARD AMIRAL COURBET   
242058  950026914           1.0                

In [40]:
list(etablissements)

['legalImmat',
 'streetNumber',
 'streetName',
 'Code Postal',
 'city',
 'isHeadquarters',
 'categoryType',
 'legalName',
 'contactName',
 'contactFirstname',
 'legalStructure',
 'categoryCode',
 'categoryLabel',
 'legalIsNonprofit',
 'employeesNb',
 'categorySize',
 'foundingYear',
 'sourceLastUpdate',
 'name',
 'stateCode',
 'financeLastDate',
 'financeLastRevenue',
 'financeLastProfit',
 'dep',
 'id_nom',
 'Code INSEE',
 'Commune',
 'Département',
 'Région',
 'Altitude Moyenne',
 'Superficie',
 'PTOT',
 'Niveau de vie Commune',
 'Niveau de vie Département',
 'HT20',
 'HT120',
 'HT220',
 'HT320',
 'HT420',
 'HT520',
 'CPG20',
 'RT20']

In [41]:
etablissements=etablissements.drop(columns=['Commune','id_nom','categoryCode','categoryLabel','legalIsNonprofit','stateCode','financeLastDate','financeLastRevenue','financeLastProfit'],axis=1)

In [42]:
etablissements

legalImmat  streetNumber                           streetName  \
0         7340516           NaN                                  NaN   
1        46412375          21.0                    RUE GEN DE GAULLE   
2        66304932           NaN                   COLLEGE DE KOUNGOU   
3        76912112           NaN                              LE COIN   
4       300443124           NaN               LIEU-DIT CAVALLO MORTO   
5       301341517           1.0                 ESPLANADE PARMENTIER   
6       301863668           NaN                     BOIS DE COULANGE   
7       302296629         146.0                      RUE ROBESPIERRE   
8       303406540           9.0                 AVENUE DE STALINGRAD   
9       303797823           NaN                  LA MARE AUX PRETRES   
10      304305519           5.0                      AVENUE DU MAINE   
11      305021909          19.0                    RUE DE LA CHARITE   
12      305426454          23.0                  RUE MARECHAL JOFFRE   
13      305836033           NaN                    CHEMIN DE LA LONE   
14      305836033           NaN                  ROUTE DE BAR LE DUC   
15      305836033          43.0                       RUE DU PLATEAU   
16      306126210           NaN                LIEU-DIT GERBIER JONC   
17      306332362          25.0                   RUE DE LA HUCHETTE   
18      306999137          27.0                      RUE DE NOAILLES   
19      307711895          15.0                      PLACE DU TERTRE   
20      308880228         361.0                  AVENUE DU 15E CORPS   
21      309408797           1.0                         RUE MAUSSIRE   
22      309654457         113.0              RUE DU MARECHAL LECLERC   
23      310187562           NaN                     ALLEE RAY GRASSI   
24      310727979           NaN               LIEU-DIT LA MARIAUDAIS   
25      311160592          30.0                COURS DE L'ILE SEGUIN   
26      311372569           NaN                         LES PLATANES   
27      311970552          13.0                  RUE DES BAS SABLONS   
28      312274426          22.0                      ROUTE IMPERIALE   
29      312732837           2.0                   PLACE JEANNE D'ARC   
...           ...           ...                                  ...   
242035  824097901           NaN                    RUE DE LA STATION   
242036  824121123           6.0                   RUE DES SERRURIERS   
242037  824145874           2.0                          R DES CAVES   
242038  824170633          49.0                      RUE JEAN MOULIN   
242039  824195283          11.0              CHEMIN DU PETIT CASTERA   
242040  824211098          28.0                          RUE BLANQUI   
242041  824240980          30.0              BOULEVARD DE SEBASTOPOL   
242042  824260178         308.0                     RUE ALBERT CAMUS   
242043  824277594          23.0                  RUE NICOLAS BOILEAU   
242044  824313852           4.0                     BOULEVARD GIRAUD   
242045  824340020          12.0                          RUE LAKANAL   
242046  824352777         243.0                 AVENUE DE VILLENEUVE   
242047  824374318          13.0                         R DE VIGNORU   
242048  824401830          55.0                  RUE DU GENERAL BUAT   
242049  824429237          12.0                         RUE DE DREUX   
242050  824462725          10.0                       R DE CHAMPEAUX   
242051  824490221         154.0                   RUE DU CHEMIN VERT   
242052  824526669          13.0                   AVENUE JEAN JAURES   
242053  824557607           3.0                          RUE BOUGEAU   
242054  824585665          17.0             BOULEVARD AMIRAL COURBET   
242055  824619936          46.0                      PLACE DU TRIPOT   
242056  947151684           NaN                    LIEU-DIT LANGMATT   
242057  950026914           1.0             BOULEVARD AMIRAL COURBET   
242058  950026914           1.0                

In [47]:
# On enregistre la table dans un fichier csv

etablissements.to_csv('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/etablissements.csv', sep = ';',index=False)

In [11]:
etablissements=pd.read_csv('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/etablissements.csv', sep = ';')

Nous avons donc la table établissements qui contient déjà pas mal d'informations sur les établissements, leur type, localisation...

Pour tout la suite de ce projet, nous allons nous concentrer sur les restaurants parisiens : 

In [58]:
parisiens=etablissements[etablissements['dep']=='75']
parisiens['arr']=parisiens['Code Postal'].apply(lambda s: s[3:] if s[3]!='0' else s[4:])

C:\Users\GUILLOT Robin\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


In [59]:
parisiens

legalImmat  streetNumber                  streetName Code Postal  \
10       304305519           5.0             AVENUE DU MAINE       75015   
17       306332362          25.0          RUE DE LA HUCHETTE       75005   
19       307711895          15.0             PLACE DU TERTRE       75018   
37       315946814           3.0   RUE DE L'ANCIENNE COMEDIE       75006   
51       318906591          11.0            RUE DE L ARRIVEE       75015   
57       319947537          14.0                RUE MABILLON       75006   
58       320228919          26.0                RUE PONCELET       75017   
85       325621605          14.0         BOULEVARD DE CLICHY       75018   
97       327848875           7.0         RUE SAINTE APOLLINE       75003   
121      331307975         110.0           RUE DE COURCELLES       75017   
124      331831826          87.0              RUE DE TURBIGO       75003   
168      340577659         102.0   AVENUE DES CHAMPS ELYSEES       75008   
191      343281945          13.0           RUE DES COURONNES       75020   
203      344928247          25.0                 RUE DE LYON       75012   
216      348415506          17.0    BOULEVARD DE MONTMORENCY       75016   
218      348535360          59.0          RUE DE TOCQUEVILLE       75017   
227      349664664         127.0                  RUE AMELOT       75011   
233      350214037          26.0           RUE DE BEAUJOLAIS       75001   
236      350488854          18.0             RUE D ABBEVILLE       75009   
237      350568242          73.0     BOULEVARD SAINT GERMAIN       75005   
240      350908810          54.0           RUE DU MONT CENIS       75018   
255      352677488          33.0               RUE ROUSSELET       75007   
258      353047418          28.0         RUE DU FER A MOULIN       75005   
280      379185382         107.0         RUE DE MENILMONTANT       75020   
300      381324714          46.0          RUE DE LA CHAPELLE       75018   
335      384739678           2.0                 RUE D'ORSEL       75018   
337      384945481           NaN          COUR SAINT EMILION       75012   
351      388135394          59.0    RUE SAINT ANDRE DES ARTS       75006   
354      388587602           2.0           RUE SAINT NICOLAS       75012   
382      391652716          26.0          RUE DE MONTMORENCY       75003   
...            ...           ...                         ...         ...   
241734   817888340          27.0               RUE GABRIELLE       75018   
241744   818155020          80.0                  RUE DU BAC       75007   
241749   818225708          80.0               RUE DU ROCHER       75008   
241761   818527640          28.0           AVENUE DE SUFFREN       75015   
241762   818554404          44.0             RUE SAINTE ANNE       75002   
241769   818688491          10.0               RUE DE NANTES       75019   
241775   818807919          13.0   RUE DE L'ANCIENNE COMEDIE       75006   
241799   819224791          20.0               AVENUE KLEBER       75116   
241806   819351123          10.0                  RUE BOULLE       75011   
241832   819783044          23.0           RUE DE WATTIGNIES       75012   
241838   819878687          23.0         BOULEVARD DE PICPUS       75012   
241862   820276616         103.0        BOULEVARD DE MAGENTA       75010   
241869   820418366          18.0            AVENUE DE VERDUN       75010   
241904   821043734           2.0         BOULEVARD HAUSSMANN       75009   
241905   821058971          10.0              RUE SAINT MARC       75002   
241909   821126232         114.0                RUE DE MEAUX       75019   
241921   821361102          24.0               RUE DE PICPUS       75012   
241928   821535127          80.0     BOULEVARD DE BELLEVILLE       75020   
241938   821740644           9.0             AVENUE GAMBETTA       75020   
241948   821911922          21.0                RUE DAGUERRE       75014   
241960   822182333          53.0         RUE DU MONTPARN

On va à cette table des établissements parisiens rajouter quelques informations. D'abord, on a pu récupérer sur le site de l'INSEE la localisation de tous les restaurants "émeraudes" de Paris, qui s'adressent aux personnes âgées essentiellement mais aussi aux personnes plus modestes, car ces restaurants pratiquent des prix selon les tranches de revenus
Il y en a en tout 43, voici la table (il s'agit là d'un fichier gson):

In [15]:
dl=gpd.read_file("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/restaurants-casvp.geojson")

In [16]:
dl

ville   code                         adresse      nom_restaurant type  \
0   PARIS  75002            8, RUE SAINT-SAUVEUR       SAINT-SAUVEUR    E   
1   PARIS  75002                 28, RUE GRAMONT             GRAMONT    E   
2   PARIS  75013             166, RUE DE TOLBIAC             TOLBIAC    E   
3   PARIS  75017           51, RUE DES EPINETTES           EPINETTES    S   
4   PARIS  75010            14, AVENUE DE VERDUN              VERDUN    E   
5   PARIS  75004           4, RUE DE L'AVE MARIA           AVE MARIA    E   
6   PARIS  75008              11, RUE MALLEVILLE  MARCHE DE L'EUROPE    S   
7   PARIS  75015                  18, RUE BARGUE        LA QUINTINIE    E   
8   PARIS  75003                 2, RUE AU MAIRE            AU MAIRE    E   
9   PARIS  75018       88, RUE JOSEPH DE MAISTRE   JOSEPH DE MAISTRE    E   
10  PARIS  75012  32, RUE DE LA BRECHE AUX LOUPS    BRECHE AUX LOUPS    E   
11  PARIS  75003              4, RUE DE LA PERLE    MADELEINE BEJART    E   
12  PARIS  75009              12, RUE DE NAVARIN             NAVARIN    E   
13  PARIS  75013             49, BOULEVARD ARAGO               ARAGO    E   
14  PARIS  75012           10, RUE EUGENIE EBOUE          SAINT-ELOI    S   
15  PARIS  75016                23, RUE JOUVENET            JOUVENET    E   
16  PARIS  75012            22, RUE DU CHAFFAULT           TOURELLES    E   
17  PARIS  75004                1, RUE DE FOURCY  AU PETIT REMOULEUR    E   
18  PARIS  75018      14-16, SQUARE CLIGNANCOURT        CLIGNANCOURT    E   
19  PARIS  75006              112, RUE DE RENNES       ANDRE MALRAUX    E   
20  PARIS  75020              18, RUE DE LA DUEE    SAINTS-SIMONIENS    E   
21  PARIS  75017                   28, RUE BAYEN              TERNES    E   
22  PARIS  75010     66, AVENUE CLAUDE VELLEFAUX    CLAUDE VELLEFAUX    S   
23  PARIS  75005     15, RUE DE LA PARCHEMINERIE           BOUTEBRIE    S   
24  PARIS  75019               32, RUE DE TANGER              TANGER    E   
25  PARIS  75014                43, RUE BEAUNIER            BEAUNIER    E   
26  PARIS  75005                 20, RUE ORTOLAN          MOUFFETARD    E   
27  PARIS  75014      55-57, RUE DU MONTPARNASSE        LES ARTISTES    S   
28  PARIS  75011                6, RUE DE CHANZY              CHANZY    S   
29  paris  75009     8, RUE DE LA TOUR DES DAMES      TOUR DES DAMES    E   
30  PARIS  75007        109, RUE SAINT-DOMINIQUE            LEPRINCE    E   
31  PARIS  75015             107, RUE DE LOURMEL          OSCAR ROTY    E   
32  PARIS  75011               33-37, RUE MERLIN          OMER TALON    E   
33  PARIS  75018             15, RUE DE LAGHOUAT             L'OASIS    E   
34  PARIS  75005     88, BOULEVARD DE PORT ROYAL          PORT ROYAL    E   
35  PARIS  75015                 4, RUE VAUGELAS            VAUGELAS    E   
36  PARIS  75005             18-22, RUE POLIVEAU  JARDIN DES PLANTES    E   
37   None  75013                            None                None    S   
38  PARIS  75013                 15, RUE CHARCOT             CHARCOT    E   
39  PARIS  75014             9, RUE DES ARBUSTES            ARBUSTES    E   
40  PARIS  75018        102, RUE DE CAULAINCOURT        CAULAINCOURT    E   
41  PARIS  75020                  2, RUE DU CLOS        SAINT-BLAISE    E   
42  PARIS  75014            203, AVENUE DU MAINE               MAINE    E   

                    geometry  
0   POINT (2.34948 48.86593)  
1   POINT (2.33703 48.87096)  
2   POINT (2.35256 48.82603)  
3   POINT (2.32334 48.89642)  
4   POINT (2.36194 48.87627)  
5   POINT (2.36053 48.85275)  
6   POINT (2.31345 48.87728)  
7   POINT (2.30718 48.83930)  
8   POINT (2.35771 48.86445)  
9   POINT (2.33046 48.89289)  
10  POINT (2.39482 48.83799)  
11  POINT (2.36193 48.85937)  
12  POINT (2.33900 48.87969)  
13  POINT (2.34538 48.83478)  
14  POINT (2.38601 48.84559)  
15  POINT (2.26536 48.84253)  
16  POINT (2.41505 48.84516)  
17  POINT (2.35880 48.85462)  
18  POINT (2.34723 48.8934

In [17]:
def streetNumber(s):
    s=str(s)
    StNb=''
    for i in s:
        if i!=',':
            StNb+=i
        else:
            return StNb
        
def streetName(s):
    s=str(s)
    i=0
    while i<len(s):
        if s[i]==',':
            return s[i+1:]
        else:
            i+=1
        
            
print(streetName('8,rue Saint-Sauveur'))
print(streetNumber('8,rue Saint-sauveur'))    

rue Saint-Sauveur
8


In [18]:
dl['streetNumber']=dl['adresse'].apply(lambda s: streetNumber(s))
dl['streetName']=dl['adresse'].apply(lambda s: streetName(s))

dl=dl.drop(columns=['adresse'],axis=1)


dl=dl.rename(columns={'code':'Code Postal'})
dl['arr']=dl['Code Postal'].apply(lambda s: s[3:] if s[3]!='0' else s[4:])

In [19]:
dl


ville Code Postal      nom_restaurant type                  geometry  \
0   PARIS       75002       SAINT-SAUVEUR    E  POINT (2.34948 48.86593)   
1   PARIS       75002             GRAMONT    E  POINT (2.33703 48.87096)   
2   PARIS       75013             TOLBIAC    E  POINT (2.35256 48.82603)   
3   PARIS       75017           EPINETTES    S  POINT (2.32334 48.89642)   
4   PARIS       75010              VERDUN    E  POINT (2.36194 48.87627)   
5   PARIS       75004           AVE MARIA    E  POINT (2.36053 48.85275)   
6   PARIS       75008  MARCHE DE L'EUROPE    S  POINT (2.31345 48.87728)   
7   PARIS       75015        LA QUINTINIE    E  POINT (2.30718 48.83930)   
8   PARIS       75003            AU MAIRE    E  POINT (2.35771 48.86445)   
9   PARIS       75018   JOSEPH DE MAISTRE    E  POINT (2.33046 48.89289)   
10  PARIS       75012    BRECHE AUX LOUPS    E  POINT (2.39482 48.83799)   
11  PARIS       75003    MADELEINE BEJART    E  POINT (2.36193 48.85937)   
12  PARIS       75009             NAVARIN    E  POINT (2.33900 48.87969)   
13  PARIS       75013               ARAGO    E  POINT (2.34538 48.83478)   
14  PARIS       75012          SAINT-ELOI    S  POINT (2.38601 48.84559)   
15  PARIS       75016            JOUVENET    E  POINT (2.26536 48.84253)   
16  PARIS       75012           TOURELLES    E  POINT (2.41505 48.84516)   
17  PARIS       75004  AU PETIT REMOULEUR    E  POINT (2.35880 48.85462)   
18  PARIS       75018        CLIGNANCOURT    E  POINT (2.34723 48.89349)   
19  PARIS       75006       ANDRE MALRAUX    E  POINT (2.32753 48.84787)   
20  PARIS       75020    SAINTS-SIMONIENS    E  POINT (2.39682 48.87127)   
21  PARIS       75017              TERNES    E  POINT (2.29332 48.88088)   
22  PARIS       75010    CLAUDE VELLEFAUX    S  POINT (2.37036 48.87695)   
23  PARIS       75005           BOUTEBRIE    S  POINT (2.34498 48.85163)   
24  PARIS       75019              TANGER    E  POINT (2.37102 48.88873)   
25  PARIS       75014            BEAUNIER    E  POINT (2.32776 48.82446)   
26  PARIS       75005          MOUFFETARD    E  POINT (2.34967 48.84323)   
27  PARIS       75014        LES ARTISTES    S  POINT (2.32559 48.84197)   
28  PARIS       75011              CHANZY    S  POINT (2.38253 48.85241)   
29  paris       75009      TOUR DES DAMES    E  POINT (2.33344 48.87781)   
30  PARIS       75007            LEPRINCE    E  POINT (2.30578 48.85930)   
31  PARIS       75015          OSCAR ROTY    E  POINT (2.28632 48.84292)   
32  PARIS       75011          OMER TALON    E  POINT (2.38454 48.86187)   
33  PARIS       75018             L'OASIS    E  POINT (2.35481 48.88784)   
34  PARIS       75005          PORT ROYAL    E  POINT (2.33925 48.83918)   
35  PARIS       75015            VAUGELAS    E  POINT (2.29492 48.83444)   
36  PARIS       75005  JARDIN DES PLANTES    E  POINT (2.35941 48.84035)   
37   None       75013                None    S                      None   
38  PARIS       75013             CHARCOT    E  POINT (2.37127 48.83074)   
39  PARIS       75014            ARBUSTES    E  POINT (2.30928 48.82843)   
40  PARIS       75018        CAULAINCOURT    E  POINT (2.33942 48.88955)   
41  PARIS       75020        SAINT-BLAISE    E  POINT (2.40610 48.85636)   
42  PARIS       75014               MAINE    E  POINT (2.32655 48.82925)   

   streetNumber                   streetName arr  
0             8            RUE SAINT-SAUVEUR   2  
1            28                  RUE GRAMONT   2  
2           166               RUE DE TOLBIAC  13  
3            51            RUE DES EPINETTES  17  
4            14             AVENUE DE VERDUN  10  
5             4           RUE DE L'AVE MARIA   4  
6            11               RUE MALLEVILLE   8  
7            18                   RUE BARGUE  15  
8             2                 RUE AU MAIRE   3  
9            88        RUE JOSEPH DE MAISTRE  18  
10           32   RUE DE LA BRECHE AUX LOUPS  12  
11            4              RUE DE LA PERLE   

Nous allons nous servir de cette table pour créer la variable nb_émeraudes, qui renseigne sur le nombre de restaurants émeraudes présents dans l'arrondissement où se situe chaque établissement de notre table

In [20]:
dl['arr'].value_counts()

18    4
5     4
14    4
13    4
15    3
12    3
9     2
2     2
17    2
3     2
20    2
4     2
11    2
10    2
19    1
16    1
6     1
7     1
8     1
Name: arr, dtype: int64

On peut maintenant créer notre variable nb_emeraudes : 


In [21]:
arr4=['18','13','5','14']                                # liste des arrondissements comportant 4 restaurants émeraudes
arr3=['12','15']
arr2=['20','4','10','17','3','11','2','9']
arr1=['8','6','16','19','7']
arr0=['1']

In [60]:
parisiens['nb_emeraudes']=parisiens['arr'].apply(lambda x: 4 if x in arr4 else 3 if x in arr3 else 2 if x in arr2 else 1 if x in arr1 else 0)

C:\Users\GUILLOT Robin\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [61]:
parisiens

legalImmat  streetNumber                  streetName Code Postal  \
10       304305519           5.0             AVENUE DU MAINE       75015   
17       306332362          25.0          RUE DE LA HUCHETTE       75005   
19       307711895          15.0             PLACE DU TERTRE       75018   
37       315946814           3.0   RUE DE L'ANCIENNE COMEDIE       75006   
51       318906591          11.0            RUE DE L ARRIVEE       75015   
57       319947537          14.0                RUE MABILLON       75006   
58       320228919          26.0                RUE PONCELET       75017   
85       325621605          14.0         BOULEVARD DE CLICHY       75018   
97       327848875           7.0         RUE SAINTE APOLLINE       75003   
121      331307975         110.0           RUE DE COURCELLES       75017   
124      331831826          87.0              RUE DE TURBIGO       75003   
168      340577659         102.0   AVENUE DES CHAMPS ELYSEES       75008   
191      343281945          13.0           RUE DES COURONNES       75020   
203      344928247          25.0                 RUE DE LYON       75012   
216      348415506          17.0    BOULEVARD DE MONTMORENCY       75016   
218      348535360          59.0          RUE DE TOCQUEVILLE       75017   
227      349664664         127.0                  RUE AMELOT       75011   
233      350214037          26.0           RUE DE BEAUJOLAIS       75001   
236      350488854          18.0             RUE D ABBEVILLE       75009   
237      350568242          73.0     BOULEVARD SAINT GERMAIN       75005   
240      350908810          54.0           RUE DU MONT CENIS       75018   
255      352677488          33.0               RUE ROUSSELET       75007   
258      353047418          28.0         RUE DU FER A MOULIN       75005   
280      379185382         107.0         RUE DE MENILMONTANT       75020   
300      381324714          46.0          RUE DE LA CHAPELLE       75018   
335      384739678           2.0                 RUE D'ORSEL       75018   
337      384945481           NaN          COUR SAINT EMILION       75012   
351      388135394          59.0    RUE SAINT ANDRE DES ARTS       75006   
354      388587602           2.0           RUE SAINT NICOLAS       75012   
382      391652716          26.0          RUE DE MONTMORENCY       75003   
...            ...           ...                         ...         ...   
241734   817888340          27.0               RUE GABRIELLE       75018   
241744   818155020          80.0                  RUE DU BAC       75007   
241749   818225708          80.0               RUE DU ROCHER       75008   
241761   818527640          28.0           AVENUE DE SUFFREN       75015   
241762   818554404          44.0             RUE SAINTE ANNE       75002   
241769   818688491          10.0               RUE DE NANTES       75019   
241775   818807919          13.0   RUE DE L'ANCIENNE COMEDIE       75006   
241799   819224791          20.0               AVENUE KLEBER       75116   
241806   819351123          10.0                  RUE BOULLE       75011   
241832   819783044          23.0           RUE DE WATTIGNIES       75012   
241838   819878687          23.0         BOULEVARD DE PICPUS       75012   
241862   820276616         103.0        BOULEVARD DE MAGENTA       75010   
241869   820418366          18.0            AVENUE DE VERDUN       75010   
241904   821043734           2.0         BOULEVARD HAUSSMANN       75009   
241905   821058971          10.0              RUE SAINT MARC       75002   
241909   821126232         114.0                RUE DE MEAUX       75019   
241921   821361102          24.0               RUE DE PICPUS       75012   
241928   821535127          80.0     BOULEVARD DE BELLEVILLE       75020   
241938   821740644           9.0             AVENUE GAMBETTA       75020   
241948   821911922          21.0                RUE DAGUERRE       75014   
241960   822182333          53.0         RUE DU MONTPARN

## Scrapping : on va essayer de compléter les dataframes par :

- sur pages jaunes : prix moyen 

- sur www.societe.com : capital social 

- sur tripadvisor : note + nb d'avis (qui renseigne sur la frequentation) + prix


In [ ]:
!pip install bs4
!pip install selenium
!pip install msedge-selenium-tool 

In [2]:
import bs4
from urllib import request
import selenium
import html5lib

In [10]:
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome import options
from selenium.webdriver.chrome.options import Options
from selenium.webdriver import ChromeOptions
from msedge.selenium_tools import Edge, EdgeOptions
from selenium.common.exceptions import NoSuchElementException

#### Récupération capital social sur societe.com

Nous récupérons les données de capital social pour les établissements en utilisant selenium. 

Pour l'exemple, en dessous on voit la sortie sur l'alogorithme appliqué sur 6000 établissements (ceux listés de 12000 à 18000)

In [12]:
options = webdriver.ChromeOptions()
options.add_argument("private")
options.add_argument("--start-maximized");
options.add_argument("--ignore-certificate-errors");
options.add_argument("--disable-popup-blocking");
options.add_argument("--incognito");
options.add_argument("--headless");



browser = webdriver.Chrome(executable_path="C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python//chromedriver",options=options)

browser.get('https://www.societe.com/')

liste=parisiens['legalImmat'].iloc[12000:18000]
capital_social=[]

cookie=browser.find_element_by_id("didomi-notice-agree-button").click()

for siren in tqdm(liste):
    
    search_bar = browser.find_element_by_id("input_search")
    search_bar.send_keys(siren + Keys.ENTER)
    
    try:
        browser.find_element_by_xpath("//p[@class = 'red' and contains (text(),'Aucune réponse pour cette recherche')]")
        capital_social.append('NaN')
        continue
        
    except NoSuchElementException:
        pass
        
    try:
        cap_soc = browser.find_element_by_id('capital-histo-description').text
        capital_social.append(cap_soc)
        
    except NoSuchElementException:
        capital_social.append('NaN')
            
              
        
        
    
print(capital_social)

browser.quit() 


100%|████████████████████████████████████████████████████████████████████████████| 6000/6000 [5:40:10<00:00,  3.40s/it]


['8 000,00 €', '1 080 000,00 €', '842 490,00 €', '7 622,00 €', '7 622,45 €', '1 500,00 €', '10 400,00 €', '10 000,00 €', '10 000,00 €', '8 000,00 €', '20 000,00 €', '1 000,00 €', '2 500,00 €', '1 000,00 €', '3 000,00 €', '11 111,00 €', '6 000,00 €', '7 500,00 €', 'NaN', '3 000,00 €', '8 000,00 €', '2 000,00 €', '232 000,00 €', '343 800,00 €', '1 000,00 €', '1 000,00 €', '8 000,00 €', '6 000,00 €', '5 000,00 €', '90 000,00 €', '110 000,00 €', '10 000,00 €', '8 000,00 €', '4 000,00 €', '1 000,00 €', '2 000,00 €', '30 000,00 €', '1 000,00 €', '1 000 000,00 €', '2 000,00 €', 'NaN', '3 000,00 €', '1 500,00 €', '127 780,00 €', '1 000,00 €', '1 000,00 €', '10 000,00 €', '1 000,00 €', '2 500,00 €', '3 000,00 €', '10 000,00 €', '10 000,00 €', 'NaN', '76 420,00 €', '68 145,00 €', '500,00 €', '1 000,00 €', '5 000,00 €', '3 000,00 €', '5 000,00 €', '4 000,00 €', '10 000,00 €', '764 373,00 €', '10 000,00 €', '3 000,00 €', '10 000,00 €', '5 000,00 €', '2 000,00 €', '200 000,00 €', '5 000,00 €', '10 

Nous avons appliqué cet algortihme en plusieurs fois (c'est-à-dire pas d'un seul coup sur tous nos établissements parisiens), mais par tranche de 2000 voire 6000 (pour l'exemple du dessus).

A chaque fois nous stockons les listes obtenus dans un fichier, avec une instruction du type : 

In [203]:
with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_12000_17999.txt', 'w') as f:
    for item in capital_social:
        f.write(str(item)+'\n')

Une fois que nous avons éxécuté notre algorithme sur tous les établissements, nous pouvons concaténer les listes stockées dans nos différents fichiers pour obtenir la liste finale du capital social sur l'ensemble de nos restaurants parisiens : 


In [41]:
with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_0_1999.txt', 'r') as f:
    l1 = f.read().splitlines()

with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_2000_3999.txt', 'r') as f:
    l2 = f.read().splitlines()

with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_4000_5999.txt', 'r') as f:
    l3 = f.read().splitlines()

with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_6000_7999.txt', 'r') as f:
    l4 = f.read().splitlines()

with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_8000_9999.txt', 'r') as f:
    l5 = f.read().splitlines()
    
with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_10000_11999.txt', 'r') as f:
    l6 = f.read().splitlines()
    
with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_12000_17999.txt', 'r') as f:
    l7 = f.read().splitlines()
    
with open('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/Données/cap_social_18000_22872.txt', 'r') as f:
    l8 = f.read().splitlines()

In [42]:
list_finale=l1+l2+l3+l4+l5+l6+l7+l8

In [43]:
len(list_finale)

22873

On peut maintenant concaténer list_finale à notre table parisiens.

Mais avant, on remet en forme nos données de capital social de sorte à avoir 
des valeurs numériques (donc le type doit être un flottant). 
Pour cela, on doit faire un certain nombre de petites opérations, parmi lesquelles supprimer le signe euro et les espaces.
On va donc appliquer une fonction transfo à notre série de données de capital_social

Pour cela, et après avoir passé en revue toutes nos données de capital_social, on a identifié certains types de cellules à prendre en compte:

In [44]:
# cellules qui contiennent la mention (minimum), assez présentes, qu'on doit supprimer dans notre fonction transfo
# Ex : 

print(list_finale[17938])


# cellules exprimées en Franc Suisse (deux en tout), on convertit en euros

print(list_finale[9122])
print(list_finale[20217])

list_finale[9122]='10230000'    # on garde une chaîne de caractères pour pouvoir appliquer notre fonction transfo() sans soucis
list_finale[20217]='10230000'


# cellules exprimées en Livre Sterling (deux en tout), on convertit en euros

print(list_finale[9322])
print(list_finale[15243])

list_finale[9322]='110'
list_finale[15243]='51366,7'

# cellule exprimée en US dollars (une en tout), on convertit en euros

print(list_finale[10037])

list_finale[10037]='830'

7 622,45 € (minimum)
11 000 000,00 Franc suisse
11 000 000,00 Franc suisse
100,00 Livre sterling
46 697,00 Livre sterling
1 000,00 Dollar US


In [62]:
# On écrit notre fonction transfo() (peut-être pas très optimisée en terme de manipulations d'expressions régulières...)

def transfo(s):
    e=re.sub('minimum','',s)
    f=re.sub('[(\s€)]','',e)
    g=re.sub(',','.',f)
    return float(g)

parisiens['Capital Social']=list_finale
parisiens['Capital Social']=parisiens['Capital Social'].apply(lambda s: transfo(s))

C:\Users\GUILLOT Robin\Anaconda3\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\GUILLOT Robin\Anaconda3\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [63]:
parisiens

legalImmat  streetNumber                  streetName Code Postal  \
10       304305519           5.0             AVENUE DU MAINE       75015   
17       306332362          25.0          RUE DE LA HUCHETTE       75005   
19       307711895          15.0             PLACE DU TERTRE       75018   
37       315946814           3.0   RUE DE L'ANCIENNE COMEDIE       75006   
51       318906591          11.0            RUE DE L ARRIVEE       75015   
57       319947537          14.0                RUE MABILLON       75006   
58       320228919          26.0                RUE PONCELET       75017   
85       325621605          14.0         BOULEVARD DE CLICHY       75018   
97       327848875           7.0         RUE SAINTE APOLLINE       75003   
121      331307975         110.0           RUE DE COURCELLES       75017   
124      331831826          87.0              RUE DE TURBIGO       75003   
168      340577659         102.0   AVENUE DES CHAMPS ELYSEES       75008   
191      343281945          13.0           RUE DES COURONNES       75020   
203      344928247          25.0                 RUE DE LYON       75012   
216      348415506          17.0    BOULEVARD DE MONTMORENCY       75016   
218      348535360          59.0          RUE DE TOCQUEVILLE       75017   
227      349664664         127.0                  RUE AMELOT       75011   
233      350214037          26.0           RUE DE BEAUJOLAIS       75001   
236      350488854          18.0             RUE D ABBEVILLE       75009   
237      350568242          73.0     BOULEVARD SAINT GERMAIN       75005   
240      350908810          54.0           RUE DU MONT CENIS       75018   
255      352677488          33.0               RUE ROUSSELET       75007   
258      353047418          28.0         RUE DU FER A MOULIN       75005   
280      379185382         107.0         RUE DE MENILMONTANT       75020   
300      381324714          46.0          RUE DE LA CHAPELLE       75018   
335      384739678           2.0                 RUE D'ORSEL       75018   
337      384945481           NaN          COUR SAINT EMILION       75012   
351      388135394          59.0    RUE SAINT ANDRE DES ARTS       75006   
354      388587602           2.0           RUE SAINT NICOLAS       75012   
382      391652716          26.0          RUE DE MONTMORENCY       75003   
...            ...           ...                         ...         ...   
241734   817888340          27.0               RUE GABRIELLE       75018   
241744   818155020          80.0                  RUE DU BAC       75007   
241749   818225708          80.0               RUE DU ROCHER       75008   
241761   818527640          28.0           AVENUE DE SUFFREN       75015   
241762   818554404          44.0             RUE SAINTE ANNE       75002   
241769   818688491          10.0               RUE DE NANTES       75019   
241775   818807919          13.0   RUE DE L'ANCIENNE COMEDIE       75006   
241799   819224791          20.0               AVENUE KLEBER       75116   
241806   819351123          10.0                  RUE BOULLE       75011   
241832   819783044          23.0           RUE DE WATTIGNIES       75012   
241838   819878687          23.0         BOULEVARD DE PICPUS       75012   
241862   820276616         103.0        BOULEVARD DE MAGENTA       75010   
241869   820418366          18.0            AVENUE DE VERDUN       75010   
241904   821043734           2.0         BOULEVARD HAUSSMANN       75009   
241905   821058971          10.0              RUE SAINT MARC       75002   
241909   821126232         114.0                RUE DE MEAUX       75019   
241921   821361102          24.0               RUE DE PICPUS       75012   
241928   821535127          80.0     BOULEVARD DE BELLEVILLE       75020   
241938   821740644           9.0             AVENUE GAMBETTA       75020   
241948   821911922          21.0                RUE DAGUERRE       75014   
241960   822182333          53.0         RUE DU MONTPARN

#### Récupération liens tripadvisor 

Nous récupérons les liens TripAdvisor des établissements en utilisant selenium.


In [ ]:
nombre_parisiens=len(parisiens)   # 22873

liens_trip_advisor=[]

for i in tqdm(range(nombre_parisiens)):  
    browser.get('https://www.google.fr/')
    search = browser.find_element_by_name('q')
    query = str(parisiens['legalName'][i]) + ' ' + 'restaurant paris tripadvisor'
    search.send_keys(query)
    search.send_keys(Keys.RETURN)
    
    try:
        browser.find_element(By.XPATH, '(//h3)[1]/../../a').click()
        liens_trip_advisor.append(browser.current_url)
        continue
    
    except NoSuchElementException:
        pass
   
    
# Certains restos ont eu comme lien le lien d'une review en particulier : 
# le code suivant permet de trouver la page globale de ces restos

 for i in tqdm(range(nombre_parisiens)): 
    if "https://www.tripadvisor.fr/ShowUserReviews" in liens_trip_advisor[i]:
        url = liens_trip_advisor[i]
        request_text = request.urlopen(url).read()
        page = bs4.BeautifulSoup(request_text, "lxml")        
        if page.find_all('span',{'class':'altHeadInline'}) != []:
            span = page.find('span',{'class':'altHeadInline'})
            if span.find('a')['href'] != []:
                href = span.find('a')['href']
                liens_trip_advisor[i] = 'https://www.tripadvisor.fr' + href
                


In [56]:
liens_trip_advisor

['https://www.tripadvisor.fr/Restaurant_Review-g187147-d1109794-Reviews-Les_Cedres_du_Liban-Paris_Ile_de_France.html',
 'https://www.tripadvisor.fr/Restaurant_Review-g187147-d3941770-Reviews-Souvlaki_Athenien-Paris_Ile_de_France.html',
 'https://www.tripadvisor.fr/Restaurant_Review-g187147-d1035528-Reviews-La_Cremaillere_1900-Paris_Ile_de_France.html',
 'https://www.tripadvisor.fr/Restaurants-g187147-Paris_Ile_de_France.html',
 'https://www.tripadvisor.fr/Restaurant_Review-g187147-d2229107-Reviews-Brioche_Doree-Paris_Ile_de_France.html',
 'https://www.tripadvisor.fr/Restaurant_Review-g187147-d718680-Reviews-La_Grille_Vintage-Paris_Ile_de_France.html',
 'https://www.google.fr/search?source=hp&ei=bV7OX-nYMoSBjLsPt4WA0AM&q=AFO+restaurant+paris+tripadvisor&oq=AFO+restaurant+paris+tripadvisor&gs_lcp=CgZwc3ktYWIQAzIICCEQFhAdEB5Q2AZYiQxggA1oAHAAeACAAfIBiAGhBJIBBTEuMC4ymAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwipw_2Cq7ztAhWEAGMBHbcCADoQ4dUDCAw&uact=5',
 'https://www.google.fr/search?sou

In [64]:
parisiens['Lien TripAdvisor']=liens_trip_advisor

C:\Users\GUILLOT Robin\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [65]:
parisiens

legalImmat  streetNumber                  streetName Code Postal  \
10       304305519           5.0             AVENUE DU MAINE       75015   
17       306332362          25.0          RUE DE LA HUCHETTE       75005   
19       307711895          15.0             PLACE DU TERTRE       75018   
37       315946814           3.0   RUE DE L'ANCIENNE COMEDIE       75006   
51       318906591          11.0            RUE DE L ARRIVEE       75015   
57       319947537          14.0                RUE MABILLON       75006   
58       320228919          26.0                RUE PONCELET       75017   
85       325621605          14.0         BOULEVARD DE CLICHY       75018   
97       327848875           7.0         RUE SAINTE APOLLINE       75003   
121      331307975         110.0           RUE DE COURCELLES       75017   
124      331831826          87.0              RUE DE TURBIGO       75003   
168      340577659         102.0   AVENUE DES CHAMPS ELYSEES       75008   
191      343281945          13.0           RUE DES COURONNES       75020   
203      344928247          25.0                 RUE DE LYON       75012   
216      348415506          17.0    BOULEVARD DE MONTMORENCY       75016   
218      348535360          59.0          RUE DE TOCQUEVILLE       75017   
227      349664664         127.0                  RUE AMELOT       75011   
233      350214037          26.0           RUE DE BEAUJOLAIS       75001   
236      350488854          18.0             RUE D ABBEVILLE       75009   
237      350568242          73.0     BOULEVARD SAINT GERMAIN       75005   
240      350908810          54.0           RUE DU MONT CENIS       75018   
255      352677488          33.0               RUE ROUSSELET       75007   
258      353047418          28.0         RUE DU FER A MOULIN       75005   
280      379185382         107.0         RUE DE MENILMONTANT       75020   
300      381324714          46.0          RUE DE LA CHAPELLE       75018   
335      384739678           2.0                 RUE D'ORSEL       75018   
337      384945481           NaN          COUR SAINT EMILION       75012   
351      388135394          59.0    RUE SAINT ANDRE DES ARTS       75006   
354      388587602           2.0           RUE SAINT NICOLAS       75012   
382      391652716          26.0          RUE DE MONTMORENCY       75003   
...            ...           ...                         ...         ...   
241734   817888340          27.0               RUE GABRIELLE       75018   
241744   818155020          80.0                  RUE DU BAC       75007   
241749   818225708          80.0               RUE DU ROCHER       75008   
241761   818527640          28.0           AVENUE DE SUFFREN       75015   
241762   818554404          44.0             RUE SAINTE ANNE       75002   
241769   818688491          10.0               RUE DE NANTES       75019   
241775   818807919          13.0   RUE DE L'ANCIENNE COMEDIE       75006   
241799   819224791          20.0               AVENUE KLEBER       75116   
241806   819351123          10.0                  RUE BOULLE       75011   
241832   819783044          23.0           RUE DE WATTIGNIES       75012   
241838   819878687          23.0         BOULEVARD DE PICPUS       75012   
241862   820276616         103.0        BOULEVARD DE MAGENTA       75010   
241869   820418366          18.0            AVENUE DE VERDUN       75010   
241904   821043734           2.0         BOULEVARD HAUSSMANN       75009   
241905   821058971          10.0              RUE SAINT MARC       75002   
241909   821126232         114.0                RUE DE MEAUX       75019   
241921   821361102          24.0               RUE DE PICPUS       75012   
241928   821535127          80.0     BOULEVARD DE BELLEVILLE       75020   
241938   821740644           9.0             AVENUE GAMBETTA       75020   
241948   821911922          21.0                RUE DAGUERRE       75014   
241960   822182333          53.0         RUE DU MONTPARN

In [66]:
#On ne garde que les restaurants dont le lien est bien une page tripadvisor : on en a 14 000 environ

parisiens= parisiens[parisiens['Lien TripAdvisor'].str.contains('https://www.tripadvisor.fr/Restaurant_Review')]

In [67]:
parisiens

legalImmat  streetNumber                  streetName Code Postal  \
10       304305519           5.0             AVENUE DU MAINE       75015   
17       306332362          25.0          RUE DE LA HUCHETTE       75005   
19       307711895          15.0             PLACE DU TERTRE       75018   
51       318906591          11.0            RUE DE L ARRIVEE       75015   
57       319947537          14.0                RUE MABILLON       75006   
97       327848875           7.0         RUE SAINTE APOLLINE       75003   
124      331831826          87.0              RUE DE TURBIGO       75003   
191      343281945          13.0           RUE DES COURONNES       75020   
227      349664664         127.0                  RUE AMELOT       75011   
237      350568242          73.0     BOULEVARD SAINT GERMAIN       75005   
240      350908810          54.0           RUE DU MONT CENIS       75018   
255      352677488          33.0               RUE ROUSSELET       75007   
300      381324714          46.0          RUE DE LA CHAPELLE       75018   
335      384739678           2.0                 RUE D'ORSEL       75018   
337      384945481           NaN          COUR SAINT EMILION       75012   
351      388135394          59.0    RUE SAINT ANDRE DES ARTS       75006   
354      388587602           2.0           RUE SAINT NICOLAS       75012   
382      391652716          26.0          RUE DE MONTMORENCY       75003   
398      393233689           1.0              RUE CAVALLOTTI       75018   
408      394409510          20.0             RUE JEAN MERMOZ       75008   
431      398650275         122.0             RUE DE BAGNOLET       75020   
441      399580653           3.0              RUE DE TURENNE       75004   
475      402574099          77.0            RUE ST DOMINIQUE       75007   
488      403998057          16.0                RUE SOUFFLOT       75005   
510      408405116          13.0      BOULEVARD SAINT MARTIN       75003   
534      410914386         154.0        AVENUE DE SAINT OUEN       75018   
576      414841478          12.0               RUE DE CLICHY       75009   
589      418005724          70.0               RUE DU ROCHER       75008   
631      421390170          97.0    BOULEVARD GOUVION ST CYR       75017   
640      422020271          26.0             RUE DES RIGOLES       75020   
...            ...           ...                         ...         ...   
241592   812702009          78.0           AVENUE EMILE ZOLA       75015   
241595   812748390         102.0    BOULEVARD DE LA VILLETTE       75019   
241603   812900280           3.0                RUE PLANCHAT       75020   
241634   813611894          19.0              RUE GAY LUSSAC       75005   
241671   814446381          80.0         RUE DE MENILMONTANT       75020   
241696   815035183          45.0               RUE DES DAMES       75017   
241703   815202528          31.0             RUE COQUILLIERE       75001   
241727   817696198         163.0          BOULEVARD LEFEBVRE       75015   
241734   817888340          27.0               RUE GABRIELLE       75018   
241744   818155020          80.0                  RUE DU BAC       75007   
241749   818225708          80.0               RUE DU ROCHER       75008   
241761   818527640          28.0           AVENUE DE SUFFREN       75015   
241762   818554404          44.0             RUE SAINTE ANNE       75002   
241769   818688491          10.0               RUE DE NANTES       75019   
241806   819351123          10.0                  RUE BOULLE       75011   
241838   819878687          23.0         BOULEVARD DE PICPUS       75012   
241862   820276616         103.0        BOULEVARD DE MAGENTA       75010   
241869   820418366          18.0            AVENUE DE VERDUN       75010   
241904   821043734           2.0         BOULEVARD HAUSSMANN       75009   
241905   821058971          10.0              RUE SAINT MARC       75002   
241909   821126232         114.0                RUE DE M

In [ ]:
parisiens.reset_index(drop = True, inplace = True)

#### Récupération sur TripAdvisor des notes, nombre d'avis et prix


##### On utilise cette fois-ci BeautifulSoup (cela est suffisant, puisqu'on a nos liens TripAdvisor)
Pour chaque lien, on va récupérer les informations du restaurant associé, plus précisément 10 informations en tout, stockées dans dans 9 listes : 

- l1 : Style de nourriture
- l2 : Note Globale
- l3 : Catégorie de prix
- l4 : Fourchette de prix
- l5 : Note de cuisine
- l6 : Note de service
- l7 : Note qualité/prix
- l8 : Note d'ambiance
- l9 : Nombre d'avis
- l10 : code postal du restaurant (variable de contrôle pour vérifier que les bons restaurants sont scrappés, mais ne sert pas pour la suite)

Pour l'exemple, en-dessous on voit la sortie de l'algorithme pour 500 restaurants environ (de 7896 à 8408) : 

In [ ]:
l1=[]
l2=[]
l3=[]
l4=[]
l5=[]
l6=[]
l7=[]
l8=[]
l9=[]
l10=[]


for i in tqdm(range(7896,8408)):         
    url = liens_trip_advisor[i]                      
    req=request.Request(url)
    webpage = request.urlopen(req).read()
    page = bs4.BeautifulSoup(webpage, "lxml")

    adress=page.find('a',{"href":"#MAPVIEW"})
    try:
        l10.append(re.sub("[^0-9]", "",str(adress.contents))[-5:])
    
    except AttributeError:
         l10.append("NR")
    
    divs = page.find('div',{'class':'page'})
    try:
        infos = divs.find_all('a')
        
        try: 
            l1.append(infos[6].contents)
            
        except TypeError:
            l1.append("NR")
        
        try:
            l2.append(infos[1].contents[0]['title'][0:3])
            
        except TypeError:
            l2.append("NR")
    
        try:
            l3.append(infos[3].contents)
        
        except:
            l3.append("NR")
            
    except AttributeError:
        l1.append("NR")
        l2.append("NR")
        l3.append("NR")
    
            
    infos2 = page.find_all('div',{"class":"_1XLfiSsv"})
    try:
        l4.append(infos2[0].contents[0])
    
    except IndexError:
        l4.append("NR") 

    infos3 = page.find_all('span',{"class":"_377onWB-"})
    if len(infos3)==0:
        l5.append("NR")
        l6.append("NR")
        l7.append("NR")
        l8.append("NR")
        
    if len(infos3)==1:
        l5.append(int(infos3[0].contents[0]['class'][1][7:])/10)
        l6.append("NR")
        l7.append("NR")
        l8.append("NR")
        
    if len(infos3) == 2:
        l5.append(int(infos3[0].contents[0]['class'][1][7:])/10)
        l6.append(int(infos3[1].contents[0]['class'][1][7:])/10)
        l7.append("NR")
        l8.append("NR")
        
        
    if len(infos3) == 3:
        l5.append(int(infos3[0].contents[0]['class'][1][7:])/10)
        l6.append(int(infos3[1].contents[0]['class'][1][7:])/10)
        l7.append(int(infos3[2].contents[0]['class'][1][7:])/10)
        l8.append("NR")
      
    if len(infos3) == 4:
        l5.append(int(infos3[0].contents[0]['class'][1][7:])/10)
        l6.append(int(infos3[1].contents[0]['class'][1][7:])/10)
        l7.append(int(infos3[2].contents[0]['class'][1][7:])/10)
        l8.append(int(infos3[3].contents[0]['class'][1][7:])/10)
    
    if len(infos3) >= 5:
        l5.append("NR")
        l6.append("NR")
        l7.append("NR")
        l8.append("NR")
        
    try:
        l9.append(re.sub("[^0-9]", "", page.find('span',{"class":"_3Wub8auF"}).text))
    except AttributeError:
        l9.append("NR")
   
 # on rajoute une condition d'arrêt : en effet, TripAdvisor nous bloque au bout de 500 itérations environ, ce qui fait que 
 # la page qu'on lui demande de requêter est vide, et l'algorithme va alors mettre que des NaN à notre liste
 # Ainsi, lorsque pour un restaurant, toutes les informations ajoutées à nos listes sont sur "NR", c'est que TripAdvicos 
 # nous a bloqués temporairement, et alors on arrête l'algorithme, et on recommence là où on s'est arrêtés
    j=i
    if l1[j]==l2[j]==l3[j]==l4[j]==l5[j]==l6[j]==l7[j]==l8[j]==l9[j]==l10[j]=="NR":
        break

In [18]:
print('Style de nourriture',l1)
print('--------------------------------------')
print('\n')
print('Note Globale',l2)
print('--------------------------------------')
print('\n')
print('Catégorie de prix',l3)
print('--------------------------------------')
print('\n')
print('Fourchette de prix',l4)
print('--------------------------------------')
print('\n')
print('Note de cuisine',l5)
print('--------------------------------------')
print('\n')
print('Note de service',l6)
print('--------------------------------------')
print('\n')
print('Note qualité-prix',l7)
print('--------------------------------------')
print('\n')
print('Note ambiance',l8)
print('--------------------------------------')
print('\n')
print('Nombre avis',l9)
print('--------------------------------------')
print('\n')
print('Code Postal',l10)
print('--------------------------------------')
print('\n')

Style de nourriture ["['Européenne']", "['Européenne']", "['27 rue Rodier, 75009 Paris France']", "['Café']", "['+ Ajouter le numéro de téléphone']", "['Plats sans gluten']", "['Méditerranéenne']", "['Asiatique']", "['Végétariens bienvenus']", "['Végétariens bienvenus']", "['Asiatique']", "['Shanghai']", "['19 Boulevard Garibaldi, 75015, 75015 Paris France']", "['27 rue Salneuve, 75017 Paris France']", "['+33 1 43 43 64 55']", "['Méditerranéenne']", "['Européenne']", "['10 Rue Mandar, 75002 Paris France']", "['Végétariens bienvenus']", "['Végétariens bienvenus']", "['Végétariens bienvenus']", "['Géorgienne']", "['Napolitaine']", "['+ Ajouter le site web']", "['Fruits de mer & Poisson']", '["62 rue d\'Orsel, 75018 Paris France"]', "['Bars-restaurants']", "['Diner']", "['+33 1 44 26 34 11']", "['+ Ajouter horaires']", "['10 Rue Du Cardinal Lemoine, 75005 Paris France']", "['+33 6 84 81 43 32']", "['+ Ajouter le site web']", '["Europe de l\'Est"]', "['Asiatique']", "['Vietnamienne']", "['

On concatène les listes finales obtenues à nottre dataframe parisiens (tous les détails ne sont pas mis ici), et on obtient finalement le dataframe suivant : 

In [19]:
parisiens=pd.read_csv("C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/semivictoire.csv",sep=";")

In [20]:
parisiens

legalImmat  streetNumber             streetName  Code Postal      city  \
0       304305519           5.0        AVENUE DU MAINE        75015  PARIS 15   
1       306332362          25.0     RUE DE LA HUCHETTE        75005   PARIS 5   
2       307711895          15.0        PLACE DU TERTRE        75018  PARIS 18   
3       318906591          11.0       RUE DE L ARRIVEE        75015  PARIS 15   
4       319947537          14.0           RUE MABILLON        75006   PARIS 6   
...           ...           ...                    ...          ...       ...   
14825   823268370          17.0             RUE VIGNON        75008   PARIS 8   
14826   823628706         115.0       BOULEVARD DAVOUT        75020  PARIS 20   
14827   823812573         248.0  RUE DU FBG ST ANTOINE        75012  PARIS 12   
14828   824340020          12.0            RUE LAKANAL        75015  PARIS 15   
14829   824490221         154.0     RUE DU CHEMIN VERT        75011  PARIS 11   

       isHeadquarters categoryType                             legalName  \
0                   1          NaN                   LES CEDRES DU LIBAN   
1                   1          NaN                  LE SOUVLAKI ATHENIEN   
2                   1          NaN          LA CREMAILLERE DE MONTMARTRE   
3                   0          NaN                      LA BRIOCHE DOREE   
4                   1          NaN  BRASSERIE DE LA GRILLE SAINT-GERMAIN   
...               ...          ...                                   ...   
14825               1          NaN                                HU JIN   
14826               1          NaN                      YASMINE D'ORIENT   
14827               1          NaN                              CHEZ XIA   
14828               1          NaN                                   SMR   
14829               1   Commerçant          PAOLINI*CHRISTOPHER EDOUARD/   

      contactName contactFirstname  ...  \
0             NaN              NaN  ...   
1             NaN              NaN  ...   
2             NaN              NaN  ...   
3             NaN              NaN  ...   
4             NaN              NaN  ...   
...           ...              ...  ...   
14825         NaN              NaN  ...   
14826         NaN              NaN  ...   
14827         NaN              NaN  ...   
14828         NaN              NaN  ...   
14829     PAOLINI      CHRISTOPHER  ...   

                                        Lien TripAdvisor  \
0      https://www.tripadvisor.fr/Restaurant_Review-g...   
1      https://www.tripadvisor.fr/Restaurant_Review-g...   
2      https://www.tripadvisor.fr/Restaurant_Review-g...   
3      https://www.tripadvisor.fr/Restaurant_Review-g...   
4      https://www.tripadvisor.fr/Restaurant_Review-g...   
...                                                  ...   
14825  https://www.tripadvisor.fr/Restaurant_Review-g...   
14826  https://www.tripadvisor.fr/Restaurant_Review-g...   
14827  https://www.tripadvisor.fr/Restaurant_Review-g...   
14828  https://www.tripadvisor.fr/Restaurant_Review-g...   
14829  https://www.tripadvisor.fr/Restaurant_Review-g...   

                                     Style de nourriture Note Globale  \
0                                              ['Saine']          4,5   
1                                  ['+33 1 43 54 96 95']          4,0   
2             ['15 Place du Tertre, 75018 Paris France']          3,5   
3                                ['Restauration rapide']          4,0   
4               ['14, rue Mabillon, 75006 Paris France']          3,0   
...                                                  ...          ...   
14825                                      ['Asiatique']          4,0   
14826                          ['Végétariens bienvenus']          4,0   
14827  ["20 Rue de Bellechasse Musee d'Orsay, 7eme, 7...          2,5   
14828                                          ['Saine']          4,0   
14829                                     ['Européenne']          3,5   

      

Recodage de certaines variables et nettoyage des sorties : on va 


1)Nettoyer la variable style de nourriture qui contient des sorties diverses et variées, comme on peut le voir au-dessus

2)Recoder la variable catégorie de prix en plusieurs modalités ("faible","moyen","élevé") selon le nombre de signe "euros"

3)Nettoyer et transformer la variable fourchette de prix en deux variables : prix minimum et prix maximum

4)Remplacer tous les Non Renseigné/NR par des NaN pour que ce soit uniformisé sur notre Dataframe

1 : Variable style de nourriture

Il s'agit plus d'une information pour compléter qui ne va pas tant nous servir...

In [107]:
args_acceptes=["Végétariens bienvenus","Espagnole","Européenne","Moyen-Orient","Cantonaise","Sicilienne"
               ,"Coréenne","Asiatique","Saine","Tunisienne","Vietnamienne","Japonaise","Thaï","Américaine","Méditerranéenne",
               "Grecque","Turque","Restauration rapide","cambodgienne"]

In [108]:
parisiens

legalImmat  streetNumber                  streetName  Code Postal  \
0       304305519           5.0             AVENUE DU MAINE        75015   
1       306332362          25.0          RUE DE LA HUCHETTE        75005   
2       307711895          15.0             PLACE DU TERTRE        75018   
3       318906591          11.0            RUE DE L ARRIVEE        75015   
4       319947537          14.0                RUE MABILLON        75006   
5       327848875           7.0         RUE SAINTE APOLLINE        75003   
6       331831826          87.0              RUE DE TURBIGO        75003   
7       343281945          13.0           RUE DES COURONNES        75020   
8       349664664         127.0                  RUE AMELOT        75011   
9       350568242          73.0     BOULEVARD SAINT GERMAIN        75005   
10      350908810          54.0           RUE DU MONT CENIS        75018   
11      352677488          33.0               RUE ROUSSELET        75007   
12      381324714          46.0          RUE DE LA CHAPELLE        75018   
13      384739678           2.0                 RUE D'ORSEL        75018   
14      384945481           NaN          COUR SAINT EMILION        75012   
15      388135394          59.0    RUE SAINT ANDRE DES ARTS        75006   
16      388587602           2.0           RUE SAINT NICOLAS        75012   
17      391652716          26.0          RUE DE MONTMORENCY        75003   
18      393233689           1.0              RUE CAVALLOTTI        75018   
19      394409510          20.0             RUE JEAN MERMOZ        75008   
20      398650275         122.0             RUE DE BAGNOLET        75020   
21      399580653           3.0              RUE DE TURENNE        75004   
22      402574099          77.0            RUE ST DOMINIQUE        75007   
23      403998057          16.0                RUE SOUFFLOT        75005   
24      408405116          13.0      BOULEVARD SAINT MARTIN        75003   
25      410914386         154.0        AVENUE DE SAINT OUEN        75018   
26      414841478          12.0               RUE DE CLICHY        75009   
27      418005724          70.0               RUE DU ROCHER        75008   
28      421390170          97.0    BOULEVARD GOUVION ST CYR        75017   
29      422020271          26.0             RUE DES RIGOLES        75020   
...           ...           ...                         ...          ...   
14800   812702009          78.0           AVENUE EMILE ZOLA        75015   
14801   812748390         102.0    BOULEVARD DE LA VILLETTE        75019   
14802   812900280           3.0                RUE PLANCHAT        75020   
14803   813611894          19.0              RUE GAY LUSSAC        75005   
14804   814446381          80.0         RUE DE MENILMONTANT        75020   
14805   815035183          45.0               RUE DES DAMES        75017   
14806   815202528          31.0             RUE COQUILLIERE        75001   
14807   817696198         163.0          BOULEVARD LEFEBVRE        75015   
14808   817888340          27.0               RUE GABRIELLE        75018   
14809   818155020          80.0                  RUE DU BAC        75007   
14810   818225708          80.0               RUE DU ROCHER        75008   
14811   818527640          28.0           AVENUE DE SUFFREN        75015   
14812   818554404          44.0             RUE SAINTE ANNE        75002   
14813   818688491          10.0               RUE DE NANTES        75019   
14814   819351123          10.0                  RUE BOULLE        75011   
14815   819878687          23.0         BOULEVARD DE PICPUS        75012   
14816   820276616         103.0        BOULEVARD DE MAGENTA        75010   
14817   820418366          18.0            AVENUE DE VERDUN        75010   
14818   821043734           2.0         BOULEVARD HAUSSMANN        75009   
14819   821058971          10.0              RUE SAINT MARC        75002   
14820   821126232         114.0                RUE DE M

In [109]:
parisiens["Style de nourriture"]=parisiens["Style de nourriture"].apply(lambda s: re.sub('[\[\]\']','',s))
parisiens["Style de nourriture"]=parisiens["Style de nourriture"].apply(lambda s: s if s in args_acceptes else 'NaN')

2 : Variable catégorie de prix

Il s'agit d'une information inmportante, quasiment toujours renseignée

Tripadvisor a 3 niveaux échelles : 

'€' : prix faible

'€€-€€€' : prix intermédiaire

'€€€€' : prix élevé

In [110]:
def transfo(s):
    if s.find('€')!=-1:
        s=re.sub('[\'-\[\]]','',s)
        if len(s)==1:
            s='faible'
        elif len(s)==4:
            s='élevé'
        else:
            s='moyen'
    
    else:
        s='NaN'
    
    return s
        
    

In [111]:
parisiens["Catégorie de prix"]=parisiens["Catégorie de prix"].apply(lambda s: transfo(s))

3 : Variable fourchettede prix

Variable également importante, moins renseignée que la précédente.

On nettoie et on crée les 3 variables : prix inf, prix sup, prix moyen


In [113]:
def transfobis(s):
    prix_inf=0
    prix_sup=0
    prix_moyen=0
    if s.find('€')==-1:
        prix_inf='NaN'
        prix_sup='NaN'
        prix_moyen='NaN'
    else:
        b=re.sub('[\s€]','',s)
        c=b.split('-')
        prix_inf=float(c[0])
        prix_sup=float(c[1])
        prix_moyen=(prix_inf+prix_sup)/2
    
    return prix_inf,prix_sup,prix_moyen
        
            

In [114]:
parisiens["Prix inf"]=parisiens["Fourchette de prix"].apply(lambda s: transfobis(s)[0])
parisiens["Prix sup"]=parisiens["Fourchette de prix"].apply(lambda s: transfobis(s)[1])
parisiens["Prix moyen"]=parisiens["Fourchette de prix"].apply(lambda s: transfobis(s)[2])
parisiens=parisiens.drop(columns=["Fourchette de prix"],axis=1)

In [115]:
parisiens=parisiens.astype({'Prix inf': float, 'Prix sup': float, 'Prix moyen':float})

In [116]:
parisiens


legalImmat  streetNumber                  streetName  Code Postal  \
0       304305519           5.0             AVENUE DU MAINE        75015   
1       306332362          25.0          RUE DE LA HUCHETTE        75005   
2       307711895          15.0             PLACE DU TERTRE        75018   
3       318906591          11.0            RUE DE L ARRIVEE        75015   
4       319947537          14.0                RUE MABILLON        75006   
5       327848875           7.0         RUE SAINTE APOLLINE        75003   
6       331831826          87.0              RUE DE TURBIGO        75003   
7       343281945          13.0           RUE DES COURONNES        75020   
8       349664664         127.0                  RUE AMELOT        75011   
9       350568242          73.0     BOULEVARD SAINT GERMAIN        75005   
10      350908810          54.0           RUE DU MONT CENIS        75018   
11      352677488          33.0               RUE ROUSSELET        75007   
12      381324714          46.0          RUE DE LA CHAPELLE        75018   
13      384739678           2.0                 RUE D'ORSEL        75018   
14      384945481           NaN          COUR SAINT EMILION        75012   
15      388135394          59.0    RUE SAINT ANDRE DES ARTS        75006   
16      388587602           2.0           RUE SAINT NICOLAS        75012   
17      391652716          26.0          RUE DE MONTMORENCY        75003   
18      393233689           1.0              RUE CAVALLOTTI        75018   
19      394409510          20.0             RUE JEAN MERMOZ        75008   
20      398650275         122.0             RUE DE BAGNOLET        75020   
21      399580653           3.0              RUE DE TURENNE        75004   
22      402574099          77.0            RUE ST DOMINIQUE        75007   
23      403998057          16.0                RUE SOUFFLOT        75005   
24      408405116          13.0      BOULEVARD SAINT MARTIN        75003   
25      410914386         154.0        AVENUE DE SAINT OUEN        75018   
26      414841478          12.0               RUE DE CLICHY        75009   
27      418005724          70.0               RUE DU ROCHER        75008   
28      421390170          97.0    BOULEVARD GOUVION ST CYR        75017   
29      422020271          26.0             RUE DES RIGOLES        75020   
...           ...           ...                         ...          ...   
14800   812702009          78.0           AVENUE EMILE ZOLA        75015   
14801   812748390         102.0    BOULEVARD DE LA VILLETTE        75019   
14802   812900280           3.0                RUE PLANCHAT        75020   
14803   813611894          19.0              RUE GAY LUSSAC        75005   
14804   814446381          80.0         RUE DE MENILMONTANT        75020   
14805   815035183          45.0               RUE DES DAMES        75017   
14806   815202528          31.0             RUE COQUILLIERE        75001   
14807   817696198         163.0          BOULEVARD LEFEBVRE        75015   
14808   817888340          27.0               RUE GABRIELLE        75018   
14809   818155020          80.0                  RUE DU BAC        75007   
14810   818225708          80.0               RUE DU ROCHER        75008   
14811   818527640          28.0           AVENUE DE SUFFREN        75015   
14812   818554404          44.0             RUE SAINTE ANNE        75002   
14813   818688491          10.0               RUE DE NANTES        75019   
14814   819351123          10.0                  RUE BOULLE        75011   
14815   819878687          23.0         BOULEVARD DE PICPUS        75012   
14816   820276616         103.0        BOULEVARD DE MAGENTA        75010   
14817   820418366          18.0            AVENUE DE VERDUN        75010   
14818   821043734           2.0         BOULEVARD HAUSSMANN        75009   
14819   821058971          10.0              RUE SAINT MARC        75002   
14820   821126232         114.0                RUE DE M

4 : On remplace tous les NR/Non renseignés par des NaN sur nos variables de notes


In [117]:
def transfoter(s):
    list=['Non renseigné','NR']
    if s in list:
        s='NaN'
    return s

In [118]:
parisiens["Note Globale"]=parisiens["Note Globale"].apply(lambda s: transfoter(s))
parisiens["Nombre avis"]=parisiens["Nombre avis"].apply(lambda s: transfoter(s))
parisiens["Note de cuisine"]=parisiens["Note de cuisine"].apply(lambda s: transfoter(s))
parisiens["Note de service"]=parisiens["Note de service"].apply(lambda s: transfoter(s))
parisiens["Note qualité-prix"]=parisiens["Note qualité-prix"].apply(lambda s: transfoter(s))
parisiens["Note ambiance"]=parisiens["Note ambiance"].apply(lambda s: transfoter(s))

In [119]:
# on transforme la variable Note Globale en valeurs numériques

parisiens["Note Globale"]=parisiens["Note Globale"].apply(lambda s: float(re.sub(',','.',str(s))))

In [120]:
parisiens

legalImmat  streetNumber                  streetName  Code Postal  \
0       304305519           5.0             AVENUE DU MAINE        75015   
1       306332362          25.0          RUE DE LA HUCHETTE        75005   
2       307711895          15.0             PLACE DU TERTRE        75018   
3       318906591          11.0            RUE DE L ARRIVEE        75015   
4       319947537          14.0                RUE MABILLON        75006   
5       327848875           7.0         RUE SAINTE APOLLINE        75003   
6       331831826          87.0              RUE DE TURBIGO        75003   
7       343281945          13.0           RUE DES COURONNES        75020   
8       349664664         127.0                  RUE AMELOT        75011   
9       350568242          73.0     BOULEVARD SAINT GERMAIN        75005   
10      350908810          54.0           RUE DU MONT CENIS        75018   
11      352677488          33.0               RUE ROUSSELET        75007   
12      381324714          46.0          RUE DE LA CHAPELLE        75018   
13      384739678           2.0                 RUE D'ORSEL        75018   
14      384945481           NaN          COUR SAINT EMILION        75012   
15      388135394          59.0    RUE SAINT ANDRE DES ARTS        75006   
16      388587602           2.0           RUE SAINT NICOLAS        75012   
17      391652716          26.0          RUE DE MONTMORENCY        75003   
18      393233689           1.0              RUE CAVALLOTTI        75018   
19      394409510          20.0             RUE JEAN MERMOZ        75008   
20      398650275         122.0             RUE DE BAGNOLET        75020   
21      399580653           3.0              RUE DE TURENNE        75004   
22      402574099          77.0            RUE ST DOMINIQUE        75007   
23      403998057          16.0                RUE SOUFFLOT        75005   
24      408405116          13.0      BOULEVARD SAINT MARTIN        75003   
25      410914386         154.0        AVENUE DE SAINT OUEN        75018   
26      414841478          12.0               RUE DE CLICHY        75009   
27      418005724          70.0               RUE DU ROCHER        75008   
28      421390170          97.0    BOULEVARD GOUVION ST CYR        75017   
29      422020271          26.0             RUE DES RIGOLES        75020   
...           ...           ...                         ...          ...   
14800   812702009          78.0           AVENUE EMILE ZOLA        75015   
14801   812748390         102.0    BOULEVARD DE LA VILLETTE        75019   
14802   812900280           3.0                RUE PLANCHAT        75020   
14803   813611894          19.0              RUE GAY LUSSAC        75005   
14804   814446381          80.0         RUE DE MENILMONTANT        75020   
14805   815035183          45.0               RUE DES DAMES        75017   
14806   815202528          31.0             RUE COQUILLIERE        75001   
14807   817696198         163.0          BOULEVARD LEFEBVRE        75015   
14808   817888340          27.0               RUE GABRIELLE        75018   
14809   818155020          80.0                  RUE DU BAC        75007   
14810   818225708          80.0               RUE DU ROCHER        75008   
14811   818527640          28.0           AVENUE DE SUFFREN        75015   
14812   818554404          44.0             RUE SAINTE ANNE        75002   
14813   818688491          10.0               RUE DE NANTES        75019   
14814   819351123          10.0                  RUE BOULLE        75011   
14815   819878687          23.0         BOULEVARD DE PICPUS        75012   
14816   820276616         103.0        BOULEVARD DE MAGENTA        75010   
14817   820418366          18.0            AVENUE DE VERDUN        75010   
14818   821043734           2.0         BOULEVARD HAUSSMANN        75009   
14819   821058971          10.0              RUE SAINT MARC        75002   
14820   821126232         114.0                RUE DE M

On ne va sélectionner ici que les restaurants. En fait, on a ici une table plus grosse qui contient les commerçants, artisans... et même parfois des établissements de soin qui n'ont rien à voir avec des restaurants...

On ne va donc garder dans la table précédente que ceux dont le "categoryType" est NaN, c'est-à-dire ceux qui ne sont pas commerçants. 
Pour ceux-là d'ailleurs, l'établissement porte leur nom : il est donc très difficile d'obtenir plus de données que ça sur ces établissements, et ce sont ceux qui correspondent aux lignes où souvent le nombre d'avis ou prix moyen n'est pas renseigné.

D'ailleurs, si on regarde seulement pour les commerçants, on voit que le capital social n'est jamais renseigné pour eux (ce qui est normal, et alors qu'il l'est quasiment pour tous les autres)

Bref, et on aurait pu le faire avant tous nos scrappings, mais on enlève les commerçants et artisans de notre table parisiens, et donc du même coup les colonnes contactName et contactFirstName qui ne sont renseignées que pour les commerçants

In [121]:
parisiens['categoryType'].fillna(0, inplace = True)
parisiens=parisiens[parisiens['categoryType']==0]

parisiens=parisiens.drop(columns=['categoryType','contactName','contactFirstname'],axis=1)

In [122]:
parisiens

legalImmat  streetNumber                  streetName  Code Postal  \
0       304305519           5.0             AVENUE DU MAINE        75015   
1       306332362          25.0          RUE DE LA HUCHETTE        75005   
2       307711895          15.0             PLACE DU TERTRE        75018   
3       318906591          11.0            RUE DE L ARRIVEE        75015   
4       319947537          14.0                RUE MABILLON        75006   
6       331831826          87.0              RUE DE TURBIGO        75003   
9       350568242          73.0     BOULEVARD SAINT GERMAIN        75005   
10      350908810          54.0           RUE DU MONT CENIS        75018   
11      352677488          33.0               RUE ROUSSELET        75007   
12      381324714          46.0          RUE DE LA CHAPELLE        75018   
13      384739678           2.0                 RUE D'ORSEL        75018   
14      384945481           NaN          COUR SAINT EMILION        75012   
15      388135394          59.0    RUE SAINT ANDRE DES ARTS        75006   
17      391652716          26.0          RUE DE MONTMORENCY        75003   
18      393233689           1.0              RUE CAVALLOTTI        75018   
19      394409510          20.0             RUE JEAN MERMOZ        75008   
20      398650275         122.0             RUE DE BAGNOLET        75020   
21      399580653           3.0              RUE DE TURENNE        75004   
22      402574099          77.0            RUE ST DOMINIQUE        75007   
23      403998057          16.0                RUE SOUFFLOT        75005   
24      408405116          13.0      BOULEVARD SAINT MARTIN        75003   
25      410914386         154.0        AVENUE DE SAINT OUEN        75018   
28      421390170          97.0    BOULEVARD GOUVION ST CYR        75017   
29      422020271          26.0             RUE DES RIGOLES        75020   
30      422292128         141.0          AVENUE DE MALAKOFF        75116   
31      422401323          50.0         RUE SAINT SEBASTIEN        75011   
32      425135928          57.0         RUE DE MENILMONTANT        75020   
34      428423339         188.0              RUE SAINT MAUR        75010   
35      428663983         294.0            RUE DE VAUGIRARD        75015   
36      429031594           8.0                    RUE BREA        75006   
...           ...           ...                         ...          ...   
14794   811698562          59.0       BOULEVARD PONIATOWSKI        75012   
14795   811903491          45.0            RUE DE RICHELIEU        75001   
14796   812073831          18.0               RUE DE MOSCOU        75008   
14797   812117117          79.0       BOULEVARD MALESHERBES        75008   
14799   812491850           9.0                  RUE BERGER        75001   
14800   812702009          78.0           AVENUE EMILE ZOLA        75015   
14801   812748390         102.0    BOULEVARD DE LA VILLETTE        75019   
14802   812900280           3.0                RUE PLANCHAT        75020   
14803   813611894          19.0              RUE GAY LUSSAC        75005   
14804   814446381          80.0         RUE DE MENILMONTANT        75020   
14805   815035183          45.0               RUE DES DAMES        75017   
14806   815202528          31.0             RUE COQUILLIERE        75001   
14807   817696198         163.0          BOULEVARD LEFEBVRE        75015   
14808   817888340          27.0               RUE GABRIELLE        75018   
14809   818155020          80.0                  RUE DU BAC        75007   
14810   818225708          80.0               RUE DU ROCHER        75008   
14811   818527640          28.0           AVENUE DE SUFFREN        75015   
14812   818554404          44.0             RUE SAINTE ANNE        75002   
14813   818688491          10.0               RUE DE NANTES        75019   
14816   820276616         103.0        BOULEVARD DE MAGENTA        75010   
14818   821043734           2.0         BOULEVARD HAUSS

Dernier petit ajustement : pour le 16ème arrondissement, le code postal est souvent donné (à tort) comme "75116" alors qu'il devrait être égal à "75016". Conséquence : pour beaucoup de restaurants du 16ème arrondissement, on n'a pas toutes les données de l'arrondissement correspondant (car le matching Code INSEE, Code Postal ne s'est pas fait correctement, le code postal ayant été mal renseigné). On remedie facilement à cela, puisqu'on connaît toutes les données sur le 16ème arrondissement 

In [123]:
# Ex pour le resto ligne 24: problème car code postal 75116

parisiens.iloc[24]

legalImmat                                                           422292128
streetNumber                                                               141
streetName                                                  AVENUE DE MALAKOFF
Code Postal                                                              75116
city                                                                  PARIS 16
isHeadquarters                                                               1
legalName                                          ACG VILLA CORSE RIVE DROITE
legalStructure                                                            SARL
employeesNb                                                                  0
categorySize                                                               PME
foundingYear                                                              1999
sourceLastUpdate                                           2015-06-25T00:00:00
name                                               A

In [124]:
# Ex pour le resto ligne 86: pas de problème car bon code postal (75016)

parisiens.iloc[86]

legalImmat                                                           512447632
streetNumber                                                               135
streetName                                                     RUE DU RANELAGH
Code Postal                                                              75016
city                                                                  PARIS 16
isHeadquarters                                                               1
legalName                                                             LA PEPPA
legalStructure                                                            SARL
employeesNb                                                                  6
categorySize                                                               PME
foundingYear                                                              2009
sourceLastUpdate                                           2009-09-08T00:00:00
name                                                

En fait, ce ne sont que pour les mauvais codes postaux en 75116, que les informations sur les arrondissements ne sont pas renseignées( variables RT20,HT20,PTOT... ): 

In [125]:
parisiens[parisiens["RT20"].isnull()==True]

legalImmat  streetNumber                     streetName  Code Postal  \
30      422292128         141.0             AVENUE DE MALAKOFF        75116   
42      439077462          54.0                  AVENUE KLEBER        75116   
126     572180149         135.0             AVENUE DE MALAKOFF        75116   
145     793904681          50.0                    RUE DECAMPS        75116   
152     801219403          54.0               RUE DE LONGCHAMP        75116   
155     808238174          11.0    RUE DU BOUQUET DE LONGCHAMP        75116   
169     820309912          26.0          RUE DE LA FAISANDERIE        75116   
174     823257225          25.0                   RUE COPERNIC        75116   
179     325414043          26.0       AVENUE PIERRE 1ER SERBIE        75116   
256     501604284           5.0          RUE DE LA MANUTENTION        75116   
288     530541812         189.0                RUE DE LA POMPE        75116   
311     753564558          18.0                  RUE LAURISTON        75116   
312     754090231          50.0                  RUE LAURISTON        75116   
354     810040345          14.0                   RUE COPERNIC        75116   
388     319672507          69.0                  AVENUE KLEBER        75116   
408     394179816          64.0               RUE DE LONGCHAMP        75116   
409     394224299          13.0                 RUE DE BASSANO        75116   
495     501137483          76.0               RUE SAINT DIDIER        75116   
540     532364783          15.0                     RUE MESNIL        75116   
560     752468033          25.0       AVENUE PIERRE 1ER SERBIE        75116   
595     808539944          23.0               RUE SAINT DIDIER        75116   
648     345375760          28.0                   RUE LE SUEUR        75116   
709     478131691           7.0           RUE EUGENE DELACROIX        75116   
742     508030384          32.0                  RUE PERGOLESE        75116   
754     518187968          84.0                  RUE LAURISTON        75116   
950     448964635           6.0              RUE GEORGES BIZET        75116   
1091    803437888          22.0                 RUE DE BASSANO        75116   
1263    524438827          73.0                  AVENUE KLEBER        75116   
1289    750583015           3.0                     RUE NICOLO        75116   
1313    799341763         176.0                RUE DE LA POMPE        75116   
...           ...           ...                            ...          ...   
13131   815175260          39.0             AVENUE VICTOR HUGO        75116   
13143   819501263          17.0                  RUE LAURISTON        75116   
13404   818826463          68.0             AVENUE DE NEW YORK        75116   
13500   483450573           9.0        BOULEVARD JULES SANDEAU        75116   
13532   509594719          14.0                     VLA HERRAN        75116   
13566   539422121          33.0                     RUE GREUZE        75116   
13612   807394671          13.0               RUE DE LONGCHAMP        75116   
13685   420636607          21.0                   RUE LE SUEUR        75116   
13695   439002759          70.0                  AVENUE KLEBER        75116   
13830   804211514           NaN   ROUTE DE LA MUETTE A NEUILLY        75116   
13841   809993793          54.0               RUE DE LONGCHAMP        75116   
13881   823093299          59.0                  AVENUE KLEBER        75116   
13937   437926751         130.0                RUE DE LA POMPE        75116   
13950   443638069          38.0                  RUE PERGOLESE        75116   
14004   512977117           9.0            RUE GUSTAVE COURBET        75116   
14036   534710728          11.0             RUE JEAN GIRAUDOUX        75116   
14055   788642064           NaN  ROUTE SEINE A BUTTE MORTEMART        75116   
14097   812527877          10.0                    RUE MIGNARD        75116   
14112   820041366          23.0                RUE DES SA

In [126]:
 # On récupère les données du 16ème arrondissement :
    
Code_postal=parisiens.iloc[86].loc["Code Postal"]              # 75016 et non pas 75116
Code_INSEE=parisiens.iloc[86].loc["Code INSEE"]
Département=parisiens.iloc[86].loc["Département"]
Région=parisiens.iloc[86].loc["Région"]
Altitude_Moyenne=parisiens.iloc[86].loc["Altitude Moyenne"]                                                            
Superficie=parisiens.iloc[86].loc["Superficie"]                                                                
PTOT=parisiens.iloc[86].loc["PTOT"]                                                                   
Niveau_de_vie_Commune=parisiens.iloc[86].loc["Niveau de vie Commune"]                                                    
Niveau_de_vie_Département=parisiens.iloc[86].loc["Niveau de vie Département"]                                             
HT20=parisiens.iloc[86].loc["HT20"]                                                                        
HT120=parisiens.iloc[86].loc["HT120"]                                                                        
HT220=parisiens.iloc[86].loc["HT220"]                                                                        
HT320=parisiens.iloc[86].loc["HT320"]                                                                      
HT420=parisiens.iloc[86].loc["HT420"]          
HT520=parisiens.iloc[86].loc["HT520"]                                                                     
CPG20=parisiens.iloc[86].loc["CPG20"]                                                                       
RT20=parisiens.iloc[86].loc["RT20"]

In [127]:
# On remplace toutes les valeurs NaN par des -1 

parisiens["Code INSEE"].fillna(-1, inplace = True)
parisiens["Département"].fillna(-1, inplace = True)
parisiens["Région"].fillna(-1, inplace = True)
parisiens["Altitude Moyenne"].fillna(-1, inplace = True)
parisiens["Superficie"].fillna(-1, inplace = True)
parisiens["PTOT"].fillna(-1, inplace = True)
parisiens["Niveau de vie Commune"].fillna(-1, inplace = True)
parisiens["Niveau de vie Département"].fillna(-1, inplace = True)
parisiens["HT20"].fillna(-1, inplace = True)
parisiens["HT120"].fillna(-1, inplace = True)
parisiens["HT220"].fillna(-1, inplace = True)
parisiens["HT320"].fillna(-1, inplace = True)
parisiens["HT420"].fillna(-1, inplace = True)
parisiens["HT520"].fillna(-1, inplace = True)
parisiens["CPG20"].fillna(-1, inplace = True)
parisiens["RT20"].fillna(-1, inplace = True)

In [128]:
parisiens["Code Postal"]=parisiens["Code Postal"].apply(lambda s: Code_postal if s==75116 else s)
parisiens["Code INSEE"]=parisiens["Code INSEE"].apply(lambda s: Code_INSEE if s==-1 else s)
parisiens["Département"]=parisiens["Département"].apply(lambda s: Département if s==-1 else s)
parisiens["Région"]=parisiens["Région"].apply(lambda s: Région if s==-1 else s)
parisiens["Altitude Moyenne"]=parisiens["Altitude Moyenne"].apply(lambda s: Altitude_Moyenne if s==-1 else s)
parisiens["Superficie"]=parisiens["Superficie"].apply(lambda s: Superficie if s==-1 else s)
parisiens["PTOT"]=parisiens["PTOT"].apply(lambda s: PTOT if s==-1 else s)
parisiens["Niveau de vie Commune"]=parisiens["Niveau de vie Commune"].apply(lambda s: Niveau_de_vie_Commune if s==-1 else s)
parisiens["Niveau de vie Département"]=parisiens["Niveau de vie Département"].apply(lambda s: Niveau_de_vie_Département if s==-1 else s)
parisiens["HT20"]=parisiens["HT20"].apply(lambda s: HT20 if s==-1 else s)
parisiens["HT120"]=parisiens["HT120"].apply(lambda s: HT120 if s==-1 else s)
parisiens["HT220"]=parisiens["HT220"].apply(lambda s: HT220 if s==-1 else s)
parisiens["HT320"]=parisiens["HT320"].apply(lambda s: HT320 if s==-1 else s)
parisiens["HT420"]=parisiens["HT420"].apply(lambda s: HT420 if s==-1 else s)
parisiens["HT520"]=parisiens["HT520"].apply(lambda s: HT520 if s==-1 else s)
parisiens["CPG20"]=parisiens["CPG20"].apply(lambda s: CPG20 if s==-1 else s)
parisiens["RT20"]=parisiens["RT20"].apply(lambda s: RT20 if s==-1 else s)

In [129]:
parisiens.iloc[24]

legalImmat                                                           422292128
streetNumber                                                               141
streetName                                                  AVENUE DE MALAKOFF
Code Postal                                                              75016
city                                                                  PARIS 16
isHeadquarters                                                               1
legalName                                          ACG VILLA CORSE RIVE DROITE
legalStructure                                                            SARL
employeesNb                                                                  0
categorySize                                                               PME
foundingYear                                                              1999
sourceLastUpdate                                           2015-06-25T00:00:00
name                                               A

C'est bon cette fois on ales données du 16ème arronissement qui apparaissent 

#### On a enfin notre table finale !!

In [130]:
# On enregistre la table dans un fichier csv

parisiens.to_csv('C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python/tablefinalisee.csv', sep = ';',index=False)

In [131]:
parisiens

legalImmat  streetNumber                  streetName  Code Postal  \
0       304305519           5.0             AVENUE DU MAINE        75015   
1       306332362          25.0          RUE DE LA HUCHETTE        75005   
2       307711895          15.0             PLACE DU TERTRE        75018   
3       318906591          11.0            RUE DE L ARRIVEE        75015   
4       319947537          14.0                RUE MABILLON        75006   
6       331831826          87.0              RUE DE TURBIGO        75003   
9       350568242          73.0     BOULEVARD SAINT GERMAIN        75005   
10      350908810          54.0           RUE DU MONT CENIS        75018   
11      352677488          33.0               RUE ROUSSELET        75007   
12      381324714          46.0          RUE DE LA CHAPELLE        75018   
13      384739678           2.0                 RUE D'ORSEL        75018   
14      384945481           NaN          COUR SAINT EMILION        75012   
15      388135394          59.0    RUE SAINT ANDRE DES ARTS        75006   
17      391652716          26.0          RUE DE MONTMORENCY        75003   
18      393233689           1.0              RUE CAVALLOTTI        75018   
19      394409510          20.0             RUE JEAN MERMOZ        75008   
20      398650275         122.0             RUE DE BAGNOLET        75020   
21      399580653           3.0              RUE DE TURENNE        75004   
22      402574099          77.0            RUE ST DOMINIQUE        75007   
23      403998057          16.0                RUE SOUFFLOT        75005   
24      408405116          13.0      BOULEVARD SAINT MARTIN        75003   
25      410914386         154.0        AVENUE DE SAINT OUEN        75018   
28      421390170          97.0    BOULEVARD GOUVION ST CYR        75017   
29      422020271          26.0             RUE DES RIGOLES        75020   
30      422292128         141.0          AVENUE DE MALAKOFF        75016   
31      422401323          50.0         RUE SAINT SEBASTIEN        75011   
32      425135928          57.0         RUE DE MENILMONTANT        75020   
34      428423339         188.0              RUE SAINT MAUR        75010   
35      428663983         294.0            RUE DE VAUGIRARD        75015   
36      429031594           8.0                    RUE BREA        75006   
...           ...           ...                         ...          ...   
14794   811698562          59.0       BOULEVARD PONIATOWSKI        75012   
14795   811903491          45.0            RUE DE RICHELIEU        75001   
14796   812073831          18.0               RUE DE MOSCOU        75008   
14797   812117117          79.0       BOULEVARD MALESHERBES        75008   
14799   812491850           9.0                  RUE BERGER        75001   
14800   812702009          78.0           AVENUE EMILE ZOLA        75015   
14801   812748390         102.0    BOULEVARD DE LA VILLETTE        75019   
14802   812900280           3.0                RUE PLANCHAT        75020   
14803   813611894          19.0              RUE GAY LUSSAC        75005   
14804   814446381          80.0         RUE DE MENILMONTANT        75020   
14805   815035183          45.0               RUE DES DAMES        75017   
14806   815202528          31.0             RUE COQUILLIERE        75001   
14807   817696198         163.0          BOULEVARD LEFEBVRE        75015   
14808   817888340          27.0               RUE GABRIELLE        75018   
14809   818155020          80.0                  RUE DU BAC        75007   
14810   818225708          80.0               RUE DU ROCHER        75008   
14811   818527640          28.0           AVENUE DE SUFFREN        75015   
14812   818554404          44.0             RUE SAINTE ANNE        75002   
14813   818688491          10.0               RUE DE NANTES        75019   
14816   820276616         103.0        BOULEVARD DE MAGENTA        75010   
14818   821043734           2.0         BOULEVARD HAUSS

NB : on a assayé également de scrapper les prix moyens sur le site des pages jaunes. Mais l'algo, qui tournait bien, a été arrêté au bout de 500 itérations environ, et contrairement à Trip Advisor, nous sommes bloqués de façon permanente. 

Nous avons essayé d'exploiter des librairies comme Fake-User-agent, qui permettent de simuler avec un degré plus ou moins élevé ce que notre ordinateur envoie au site lorsqu'il s'agit d'un utilisateur réel. Nous avons un peu expériementé cette solution, en essayant par exemple de jouer sur les headers de la requête, avec un User-Agent répandu et pouvant appartenir à un vrai utilisateur. Ces tentatives n'ont pas marché sur le site des pages jaunes... Nous avons également essayé d'imposer des temps d'attente à notre webdriver, pour que celui-ci n'apparaisse pas trop "pressé" et ne soit pas directement classé comme robot ; sans succès.
On peut aller plus loin, en se servant de proxys gratuits par exemple, en jouant sur des adresses IP tournantes... mais on tombe dans un tout autre domaine...

#### Récupération prix moyen sur pages jaunes

In [ ]:
edge_options = EdgeOptions()                                   # Edge pour changer de Chrome...
edge_options.use_chromium = True
edge_options.add_argument("private")
edge_options.add_argument("--start-maximized");
edge_options.add_argument("--ignore-certificate-errors");
edge_options.add_argument("--disable-popup-blocking");
edge_options.add_argument("--incognito");





browser = Edge(executable_path="C:/Users/GUILLOT Robin/Documents/Robin Ensae/Matières/Python//msedgedriver",options=edge_options)




browser.get('https://www.pagesjaunes.fr/activites')

cookie=browser.find_element_by_id("didomi-notice-agree-button").click()

sleep(5)

prix_moy=[]


for k in tqdm(range(0,449)):                      # on a été bloqués au bout du 449ème restaurant
    
    nom=parisiens.iloc[k].loc['legalName']
    code_post=parisiens.iloc[k].loc['postalCode']
    
    search_bar_une = browser.find_element_by_id("quoiqui")
    search_bar_une.send_keys(nom)
    
    search_bar_deux = browser.find_element_by_id("ou")
    search_bar_deux.send_keys(code_post + Keys.ENTER)
        
    try:
        sleep(1)
        donnee = browser.find_element_by_xpath("//div[@class = 'zone-cvi-cviv']/p[1]").text
        prix_moy.append(donnee)
        
    except NoSuchElementException:
        prix_moy.append('NaN')
        
    search_bar_une_nettoyee = browser.find_element_by_id("quoiqui").clear()
    search_bar_deux_nettoyee = browser.find_element_by_id("ou").clear()
        
            
browser.quit()

In [23]:
prix_moy

['Budget : 21-30 euros',
 'Budget : 16-20 euros',
 'Budget : 31-45 euros',
 'Prestations : nettoyage écologique, repassage, teinturerie, nettoyage de tapis, nettoyage rideaux, nettoyage du daim, nettoyage du cuir, retouches, couture, parking, nettoyage robe de mariée, accès handicapé',
 'Budget : Inférieur à 10 euros',
 'Budget : 31-45 euros',
 'Budget : 31-45 euros',
 'NaN',
 'NaN',
 'Produits : Smoking, Costume, Chemise, Pantalon, Blazer, Parkas, Accessoires, Jeans, Polo, Manteaux, tenue de soirée',
 'Budget : 21-30 euros',
 'NaN',
 'NaN',
 'NaN',
 'Prestations : Clinique, Traitement des pathologies du genou, Chirurgie du genou, Sur rendez-vous, clinique de médecine du sport, service de radiologie, service de rhumatologie',
 'Prestations : terrasse, restaurant repas de groupe',
 'NaN',
 "Prestations : Vente en ligne ou par téléphone de billets de spectacles, Présentation en ligne d'événements",
 'Type de cuisine : restaurant oriental',
 'Type de cuisine : cuisine française, restauran